/**
 * Arabic (Saudi) translations.
 *
 * Voice: Natural Saudi product Arabic — clean, warm, confident, trustworthy.
 * Not textbook MSA. Not Egyptian. Not Levantine. One Saudi voice throughout.
 */
export const STRINGS_AR = {
  // ─── Dashboard ──────────────────────────────────────────
  DASHBOARD_TITLE: 'الرئيسية',
  TOTAL_INCOME: 'إجمالي الدخل',
  TOTAL_SPENT: 'إجمالي المصاريف',
  NET_BALANCE: 'صافي الرصيد',
  SPENDING_BY_CATEGORY: 'المصاريف حسب الفئة',
  RECENT_TRANSACTIONS: 'آخر العمليات',
  AI_INSIGHTS: 'تحليل ذكي',
  SEE_ALL: 'عرض الكل',
  THIS_MONTH: 'هالشهر',

  // ─── Commitments ────────────────────────────────────────
  COMMITMENTS_THIS_MONTH: 'التزامات هالشهر',
  COMMITMENTS_NEARLY_DUE: 'قرب موعدها',
  COMMITMENTS_UPCOMING: 'الشهر الجاي',
  NO_COMMITMENTS: 'ما عندك التزامات',
  NO_COMMITMENTS_DESC: 'أضف مصاريفك الثابتة مثل الإيجار والاشتراكات والأقساط.',
  MARK_PAID: 'تم الدفع',

  // ─── Empty States ───────────────────────────────────────
  NO_TRANSACTIONS: 'ما فيه عمليات للحين',
  NO_TRANSACTIONS_DESC: 'أضف أول عملية عشان تشوف ملخص مصاريفك.',
  NO_INSIGHTS: 'ما فيه تحليلات للحين',
  NO_INSIGHTS_DESC: 'استمر بتسجيل مصاريفك عشان نعطيك تحليلات مخصصة.',

  // ─── Errors ─────────────────────────────────────────────
  ERROR_LOADING_DASHBOARD: 'ما قدرنا نحمّل البيانات',
  ERROR_GENERIC: 'صار خطأ، حاول مرة ثانية',
  RETRY: 'حاول مرة ثانية',

  // ─── Auth ───────────────────────────────────────────────
  LOGIN_TITLE: 'حياك الله',
  LOGIN_SUBTITLE: 'سجّل دخولك عشان تدير محفظتك',
  REGISTER_TITLE: 'حساب جديد',
  REGISTER_SUBTITLE: 'ابدأ تتابع مصاريفك من اليوم',
  EMAIL_LABEL: 'الإيميل',
  EMAIL_PLACEHOLDER: 'example@mail.com',
  PASSWORD_LABEL: 'كلمة المرور',
  PASSWORD_PLACEHOLDER: '••••••••',
  FULL_NAME_LABEL: 'الاسم الكامل',
  FULL_NAME_PLACEHOLDER: 'محمد العلي',
  LOGIN_BUTTON: 'تسجيل دخول',
  REGISTER_BUTTON: 'إنشاء حساب',
  LOGIN_LINK: 'عندك حساب؟ سجّل دخولك',
  REGISTER_LINK: 'ما عندك حساب؟ سجّل الحين',
  LOGOUT_BUTTON: 'تسجيل خروج',
  AUTH_ERROR_INVALID_CREDENTIALS: 'الإيميل أو كلمة المرور غلط',
  AUTH_ERROR_EMAIL_TAKEN: 'فيه حساب مسجّل بهالإيميل',
  AUTH_ERROR_WEAK_PASSWORD: 'كلمة المرور لازم تكون ٨ أحرف على الأقل',
  AUTH_ERROR_INVALID_EMAIL: 'ادخل إيميل صحيح',
  AUTH_ERROR_NAME_REQUIRED: 'الاسم الكامل مطلوب',
  AUTH_ERROR_PHONE_REQUIRED: 'رقم الجوال مطلوب',
  AUTH_ERROR_PHONE_INVALID: 'ادخل رقم جوال صحيح',

  // ─── Onboarding ────────────────────────────────────────
  ONBOARDING_TITLE: 'إعداد محفظتك',
  ONBOARDING_SUBTITLE: 'اختر بلدك وعملتك عشان نبدأ',
  ONBOARDING_CONTINUE: 'متابعة',
  ONBOARDING_CURRENCY_LABEL: 'العملة',
  ONBOARDING_COUNTRY_LABEL: 'البلد',
  ONBOARDING_LOADING: 'جاري الإعداد…',
  ONBOARDING_LOADING_TITLE: 'جاري إعداد محفظتك',
  ONBOARDING_LOADING_SUBTITLE: 'ثواني ويخلص',

  // ─── Profile / Feature Cards ────────────────────────────
  PROFILE_GOALS: 'الأهداف',
  PROFILE_SUBSCRIPTIONS: 'اشتراكات',
  PROFILE_BILL_SPLIT: 'تقسيم',
  GOALS_ON_TRACK: 'ماشي',
  GOALS_AT_RISK: 'متجاوز',
  GOALS_TRACK_BUDGETS: 'تابع ميزانيتك',
  SUBS_ACTIVE: 'نشط',
  SUBS_TRACK_RECURRING: 'تابع الدفعات',
  SPLIT_GROUP: 'مجموعة',
  SPLIT_GROUPS: 'مجموعات',
  SPLIT_WITH_FRIENDS: 'قسّم مع ربعك',

  // ─── Settings / Preferences ─────────────────────────────
  SETTINGS_PREFERENCES: 'الإعدادات',
  SETTINGS_CURRENCY: 'العملة',
  SETTINGS_APPEARANCE: 'المظهر',
  SETTINGS_LANGUAGE: 'اللغة',
  SETTINGS_ACCOUNTS: 'الحسابات',
  SETTINGS_TOTAL_BALANCE: 'إجمالي الرصيد',
  SETTINGS_ADD_ACCOUNT: 'أضف حساب',
  SETTINGS_WHATSAPP: 'واتساب',
  SETTINGS_SMS_AUTOMATION: 'رسائل البنك',
  SETTINGS_TRASH: 'المحذوفات',
  SETTINGS_TRASH_DESC: 'استرجع العمليات المحذوفة خلال ٧ أيام',
  SETTINGS_CATEGORIZE_BY_MERCHANT: 'التصنيف حسب التاجر',
  SETTINGS_CATEGORIZE_BY_MERCHANT_DESC: 'يتعلم من أول تصنيف تختاره لكل تاجر',
  SETTINGS_STATUS_ON: 'مفعل',
  SETTINGS_STATUS_OFF: 'موقّف',

  // ─── Tabs ───────────────────────────────────────────────
  TAB_HOME: 'الرئيسية',
  TAB_TRANSACTIONS: 'العمليات',
  TAB_ANALYTICS: 'التحليلات',
  TAB_COINS: 'الأصول',
  TAB_PROFILE: 'حسابي',
  TAB_FEATURES: 'الخدمات',

  // ─── Features Tab ───────────────────────────────────────
  FEATURES_HEADER: 'الخدمات',
  FEATURES_SUBS_NEXT_UP: 'القادم',
  FEATURES_SUBS_NO_ACTIVE: 'ما عندك اشتراكات نشطة',
  FEATURES_GOALS_ON_TRACK: 'في المسار',
  FEATURES_GOALS_EXCEEDED: 'تجاوزت',
  FEATURES_GOALS_NO_GOALS: 'ما عندك ميزانيات',
  FEATURES_GOALS_AT_RISK: 'في خطر',
  FEATURES_SPLIT_COMMUNITIES: 'مجموعات',
  FEATURES_SPLIT_NO_GROUPS: 'ما عندك مجموعات بعد',
  FEATURES_SPLIT_MEMBERS: 'أعضاء',
  FEATURES_CHARITY_TITLE: 'الصدقات والعطاء',
  FEATURES_CHARITY_THIS_MONTH: 'هذا الشهر',
  FEATURES_CHARITY_THIS_YEAR: 'هذه السنة',
  FEATURES_CHARITY_DONATIONS: 'صدقات',
  FEATURES_CHARITY_NO_GIVING: 'ما فيه عطاء مسجل هذا الشهر',
  FEATURES_CHARITY_TARGET: 'الهدف الشهري',
  FEATURES_CHARITY_NO_TARGET: 'حدد هدف شهري للعطاء',
  FEATURES_CHARITY_REMAINING: 'متبقي',
  FEATURES_CHARITY_OVER_BY: 'تجاوزت بـ',
  FEATURES_CHARITY_TOP: 'أكثر فئة',
  CHARITY_SCREEN_TITLE: 'الصدقات والعطاء',
  CHARITY_DAILY_TREND: 'العطاء اليومي',
  CHARITY_RECENT: 'آخر الصدقات',
  CHARITY_EMPTY_HEADLINE: 'ما فيه صدقات بعد',
  CHARITY_EMPTY_DESC: 'اضغط الزر تحت وسجل أول صدقة.',
  CHARITY_ADD_DONATION: 'إضافة صدقة',
  CHARITY_SET_TARGET_CTA: 'حدد هدف شهري',
  CHARITY_TARGET_HINT: 'أنشئ ميزانية على فئة صدقة من شاشة الأهداف لتحديد الهدف الشهري.',
  FEATURES_SUBHEADER: 'أدواتك ورؤاك',
  GOALS_TOTAL: 'إجمالي الأهداف',
  NEAR_LIMIT: 'قرب الحد',
  ALL_ON_TRACK: 'الكل في المسار',
  TXN_CLOSE: 'إغلاق',

  // ─── Smart Input ────────────────────────────────────────
  SMART_INPUT_TITLE: 'إدخال ذكي',
  SMART_INPUT_PLACEHOLDER: 'اكتب العملية...',
  SMART_INPUT_PASTE: 'لصق',
  SMART_INPUT_PASTE_DESC: 'رسالة / نص',
  SMART_INPUT_VOICE: 'صوت',
  SMART_INPUT_VOICE_DESC: 'المايك',
  SMART_INPUT_SCAN: 'مسح',
  SMART_INPUT_SCAN_DESC: 'فاتورة',
  SMART_INPUT_PARSE: 'حلّل',
  SMART_INPUT_STOP: 'إيقاف',
  SMART_INPUT_RESET: 'من جديد',
  SMART_INPUT_PLACEHOLDER_FULL: 'اكتب العملية...\n"دفعت ١٥٠ ريال كارفور"\n"راتب ٨٠٠٠ ريال وصل"',
  SMART_INPUT_TRANSCRIBING: 'جاري تحويل الصوت…',
  SMART_INPUT_TRANSCRIBING_DESC: 'نحلّل الكلام بالذكاء الاصطناعي',
  SMART_INPUT_SCANNING_DESC: 'نستخرج التفاصيل من الصورة',
  SMART_INPUT_PARSING: 'جاري تحليل المدخل…',
  SMART_INPUT_PARSING_DESC: 'الذكاء الاصطناعي يقرأ عمليتك',
  SMART_INPUT_SUCCESS_ONE: 'تمت إضافة العملية بنجاح',
  SMART_INPUT_SUCCESS_MANY: 'عمليات تمت إضافتها بنجاح',
  SMART_INPUT_RECORDS_UPDATED: 'تم تحديث سجلاتك.',
  SMART_INPUT_ADD_ANOTHER: 'أضف عملية ثانية',
  SMART_INPUT_VIEW_TRANSACTIONS: 'عرض العمليات',
  SMART_INPUT_BACK_DASHBOARD: 'رجوع للرئيسية',

  // ─── Transaction Filters ────────────────────────────────
  FILTER_ALL: 'الكل',
  FILTER_EXPENSES: 'المصاريف',
  FILTER_INCOME: 'الدخل',
  FILTER_TRANSFERS: 'التحويلات',

  // ─── FeatureGate ────────────────────────────────────────
  FEATURE_AVAILABLE_IN: 'متوفرة في باقة',
  FEATURE_UPGRADE_UNLOCK: 'ترقّى عشان تفتح هالميزة',
  FEATURE_UPGRADE_TO: 'ترقّى لباقة',

  // ─── Analytics ──────────────────────────────────────────
  ANALYTICS_TITLE: 'التحليلات',
  ANALYTICS_SUBTITLE: 'فهم أعمق لمصاريفك',
  SPENDING_ANALYSIS: 'تحليل المصاريف',
  SPENDING_ANALYSIS_DESC: 'وين راحت فلوسك هالشهر',
  STAT_TXN_COUNT: 'العمليات',
  STAT_HABITS_RECURRING: 'متكررة',
  STAT_AVG_PER_DAY: 'معدل/يوم',
  REGION_BENCHMARK_TITLE: 'مقارنة بالناس اللي مثلك',
  REGION_BENCHMARK_DESC: 'بالنسبة لفئتك العمرية في منطقتك',
  REGION_BENCHMARK_HIGHER: 'أعلى من المعدّل',
  REGION_BENCHMARK_LOWER: 'أقل من المعدّل',
  REGION_BENCHMARK_NO_DATA: 'ما عندنا بيانات كافية لمنطقتك للحين.',
  SUBSCRIPTION_SAVINGS_TITLE: 'وفّر على اشتراكاتك',
  SUBSCRIPTION_SAVINGS_DESC: 'حسب طريقة استخدامك، فيه باقات أوفر',
  SUBSCRIPTION_SAVINGS_SWITCH_TO: 'حوّل إلى',
  SUBSCRIPTION_SAVINGS_SAVE: 'توفّر',
  SUBSCRIPTION_SAVINGS_PER_YEAR: '/سنة',
  SUBSCRIPTION_SAVINGS_NO_INSIGHTS: 'ما فيه فرص توفير حالياً. بنواصل المراجعة.',
  PLAN_TYPE_INDIVIDUAL: 'فردي',
  PLAN_TYPE_FAMILY: 'عائلي',
  PLAN_TYPE_STUDENT: 'طلاب',
  PLAN_TYPE_BUNDLE: 'باقة',
  MONEY_ANALYSIS: 'تحليل المصاريف',
  SAVING_TIPS: 'نصائح التوفير',
  SUBSCRIPTIONS: 'الاشتراكات',
  TRANSACTIONS_LABEL: 'العمليات',
  HABITS_LABEL: 'العادات',
  TOP_CATEGORY: 'أعلى فئة',
  BUDGETS: 'الميزانيات',
  ON_TRACK: 'ماشي',
  AT_RISK: 'متجاوز',
  SAVED: 'وفّرت',
  DEFICIT: 'عجز',
  BUDGET_STATUS: 'حالة الميزانية',
  EXPENSE_TREND: 'اتجاه المصاريف',
  TREND_DAILY: 'يومي',
  TREND_WEEKLY: 'أسبوعي',
  TREND_MONTHLY: 'شهري',
  NO_EXPENSES_YET: 'ما فيه مصاريف لسه',
  SPENDING_HABITS: 'عادات الصرف',
  SPENDING_PATTERNS: 'أنماط صرفك',
  SPENDING_PATTERNS_DESC: 'هالأنماط تتكرر في مصاريفك وتستاهل تنتبه لها.',
  ADD_TXN_ANALYSIS: 'أضف عمليات عشان تشوف تحليل مصاريفك.',
  NO_DATA_MONTH: 'ما فيه بيانات لهالشهر للحين.',
  // Saving Tips
  PEERS_SPEND_LESS: 'صرفك على',
  PEERS_THAN_YOU: 'أعلى من الناس اللي بعمرك وفي منطقتك.',
  IF_REDUCED_5: 'لو خفّضت ٥٪ توفّر',
  PER_MONTH: '/شهر',
  BIGGEST_SPEND: 'أكبر مصاريفك على',
  SMALL_CUT: '. تقليل بسيط هنا يفرق معك.',
  ADD_TXN_TIPS: 'أضف عمليات عشان تحصل نصائح توفير.',
  NOT_ENOUGH_DATA: 'ما فيه بيانات كافية لفئتك العمرية ومنطقتك للحين.\nراجعنا الشهر الجاي.',
  SAVING_OPPORTUNITY: 'فرصة توفير',
  CUT_OVERSPENDING: 'لو خفّضت صرفك في',
  CUT_OVERSPENDING_SUFFIX: 'بس ٥٪، تقدر توفّر',
  PER_YEAR_LABEL: '/سنة',
  WHERE_SAVE: 'وين تقدر توفّر؟',
  WHERE_CUT: 'وين تقدر تقلّل؟',
  FIVE_PCT_CUT: 'تخفيض ٥٪ ←',
  COMPARED_MORE: 'مقارنة بالناس اللي بعمرك وفي منطقتك، صرفك',
  MORE_ON_THIS: 'أكثر على هالفئة.',
  MORE_PERCENT: '٪ أكثر',
  LESS_PERCENT: '٪ أقل',
  HOW_COMPARE: 'مقارنتك بغيرك',
  HOW_COMPARE_DESC: 'مقارنة بالناس اللي بعمرك وفي منطقتك:',
  GREAT_JOB: 'ممتاز!',
  SPENDING_BELOW: 'صرفك أقل أو يساوي معدّل الناس اللي بعمرك وفي منطقتك.',
  YOU: 'أنت',
  TYPICAL: 'المعدّل',
  // Subscriptions
  ACTIVE: 'نشط',
  DUE_THIS_MONTH_SUBS: 'مستحقة هالشهر',
  NO_SUBS_YET: 'ما عندك اشتراكات للحين',
  NO_SUBS_ADDED: 'ما عندك اشتراكات للحين.\nروح صفحة الاشتراكات وأضفها.',
  PER_YEAR: 'سنوياً',
  BILLING_SPLIT: 'توزيع الفواتير',
  MONTHLY_LABEL: 'شهري',
  QUARTERLY_LABEL: 'ربع سنوي',
  YEARLY_LABEL: 'سنوي',
  UPCOMING_BILLING: 'الفواتير القادمة',
  IN_DAYS: 'بعد',
  PAUSED: 'متوقف',

  // ─── Assets ─────────────────────────────────────────────
  TOTAL_ASSET_VALUE: 'إجمالي قيمة الأصول',
  GOLD: 'ذهب',
  SILVER: 'فضة',
  CRYPTO: 'عملات رقمية',
  STOCKS: 'أسهم',
  TRACK_ASSETS: 'تتبّع أصولك',
  TRACK_ASSETS_DESC: 'أضف ذهب أو فضة أو عملات رقمية',
  ADD: 'أضف',
  ASSETS_TITLE: 'الأصول',
  ASSETS_PHYSICAL: 'الأصول المادية',
  ASSETS_STOCKS: 'الأسهم',
  STOCKS_SUBTITLE: 'الأسهم الشائعة · أضف المفضلة',
  ASSETS_COMMODITIES_CRYPTO: 'السلع والعملات الرقمية',
  ASSETS_LIVE_PRICES: 'أسعار السوق الحية',
  ASSETS_BREAKDOWN: 'توزيع الأصول',
  NO_DATA: 'لا توجد بيانات',
  ADD_ASSET: 'إضافة أصل',
  ASSET_TYPE: 'نوع الأصل',
  UNIT: 'الوحدة',
  QUANTITY: 'الكمية',
  AVG_BUY_PRICE: 'متوسط سعر الشراء',
  OPTIONAL_PER: 'اختياري، لكل',
  SAVE_CHANGES: 'حفظ التعديلات',
  DELETE_ASSET: 'حذف الأصل',
  DELETE_ASSET_CONFIRM: 'تبي تحذفه من محفظتك؟',
  CANCEL: 'إلغاء',
  DELETE: 'حذف',
  INSIGHTS: 'رؤى',
  CURRENT_PRICE: 'السعر الحالي',
  CURRENT_VALUE: 'القيمة الحالية',
  LEAVE_EMPTY_REMOVE: 'اتركه فاضي عشان ينحذف',
  FAILED_LOAD_ASSETS: 'ما قدرنا نحمّل الأصول',
  INSIGHT_GOLD_HEAVY: 'محفظتك مركّزة على الذهب بشكل كبير. فكّر تنوّع في أصول ثانية.',
  INSIGHT_CRYPTO_HEAVY: 'العملات الرقمية تشكّل معظم محفظتك. أصل متقلّب — فكّر توازنه مع أصول مستقرة مثل الذهب.',
  INSIGHT_STOCK_HEAVY: 'الأسهم هي معظم استثماراتك حالياً. انتبه لتركّز القطاعات.',
  INSIGHT_DIVERSIFIED: 'تنويع ممتاز! عندك معادن وعملات رقمية وأسهم.',
  INSIGHT_PORTFOLIO_UP: 'محفظتك ارتفعت',
  INSIGHT_PORTFOLIO_DOWN: 'محفظتك انخفضت',
  INSIGHT_FROM_BUY: 'عن أسعار الشراء.',
  INSIGHT_HOLD_STEADY: 'عن أسعار الشراء. لا تقلق — الأسواق تتقلّب.',
  INSIGHT_ADD_BUY_PRICE: 'أضف أسعار الشراء لـ',
  INSIGHT_TRACK_GAINS: 'عشان تتبّع الأرباح والخسائر.',
  PHYSICAL_ASSETS: 'الأصول المادية',
  YOUR_HOLDINGS: 'ممتلكاتك',
  PORTFOLIO: 'المحفظة',
  LAST_30_DAYS: 'آخر ٣٠ يوم',
  ADD_HOLDING_PROMPT: 'وش تبي تضيف؟',
  ADD_HOLDING_ASSET_DESC: 'ذهب، فضة، BTC، ETH',
  ADD_HOLDING_STOCK_DESC: 'تتبّع الأسهم اللي عندك',
  TIME_DAY: 'يوم',
  TIME_WEEK: 'أسبوع',
  TIME_MONTH: 'شهر',
  TIME_3M: '٣ أشهر',
  TIME_YEAR: 'سنة',
  TIME_ALL: 'الكل',
  SHARES_UNIT: 'سهم',
  AI_ASSETS_FORECAST: 'توقعات AI للأصول',
  AI_ASSETS_FORECAST_DESC: 'متوفر في باقة Max · ترقّى لتفتح',
  UPGRADE_CTA: 'ترقّى',
  ASSETS_SUBTITLE: 'محفظتك الاستثمارية',
  WINNING_ASSET_THIS_MONTH: 'أفضل أصل هذا الشهر',
  LIVE_METAL_CRYPTO_PRICES: 'أسعار الذهب والعملات الرقمية',
  LIVE_STOCK_PRICES: 'أسعار الأسهم',
  SMART_INSIGHTS: 'ملاحظات سريعة',
  INSIGHT_CONCENTRATION_SENTENCE: 'يشكّل {name} نسبة {pct}٪ من إجمالي محفظتك.',
  INSIGHT_CONCENTRATION_WARN: 'فكّر في تنويع استثماراتك على فئات أصول أخرى.',
  INSIGHT_OVERALL_UP_SENTENCE: 'محفظتك ارتفعت بنسبة {pct}٪ مقارنةً بأسعار الشراء.',
  INSIGHT_OVERALL_DOWN_SENTENCE: 'محفظتك انخفضت بنسبة {pct}٪ مقارنةً بأسعار الشراء.',
  INSIGHT_BEST_GAINER_SENTENCE: 'يتصدّر {name} أصولك بارتفاع {pct}٪.',
  INSIGHT_NO_BUY_PRICES: 'أضف أسعار الشراء لأصولك لعرض إجمالي العائد.',
  DIST_STOCKS: 'أسهم',
  DIST_GOLD: 'ذهب',
  DIST_CRYPTO: 'كريبتو',
  DIST_SILVER: 'فضة',
  DIST_OTHER: 'أخرى',
  PORTFOLIO_ALLOCATION_TITLE: 'توزيع المحفظة',
  PORTFOLIO_TOTAL_LABEL: 'الإجمالي',
  SHOW_ALL: 'عرض الكل',
  SHOW_LESS: 'عرض أقل',
  CURRENCY_TOGGLE_LOCAL: 'محلي',
  CURRENCY_TOGGLE_USD: 'دولار',
  ENTER_PRICE_IN: 'أدخل السعر بـ',
  DEV_TOOLS_SECTION: 'أدوات المطوّر',
  DEV_PLAN_LABEL: 'محاكاة الخطة',
  DEV_PLAN_HINT: 'تجاوز الخطة النشطة للاختبار',
  LAST_UPDATED: 'آخر تحديث',
  PER_MONTH_SHORT: '/شهر',
  PER_QUARTER_SHORT: '/٣شهور',
  PER_YEAR_SHORT: '/سنة',
  ALL_FILTER: 'الكل',

  // ─── Add Transaction ────────────────────────────────────
  ADD_TRANSACTION: 'إضافة عملية',
  AMOUNT: 'المبلغ',
  TYPE: 'النوع',
  NOTES: 'ملاحظات',
  MERCHANT: 'المتجر',
  DESCRIPTION: 'الوصف',
  DESCRIPTION_PLACEHOLDER: 'مثلاً: بقالة',
  CATEGORY: 'الفئة',
  ACCOUNT: 'الحساب',
  ACCOUNT_OPTIONAL: '(اختياري)',
  DATE: 'التاريخ',
  NOTES_OPTIONAL: 'ملاحظات (اختياري)',
  NOTE_PLACEHOLDER: 'أضف ملاحظة…',
  SAVING: 'جاري الحفظ…',
  ADD_EXPENSE: 'أضف مصروف',
  ADD_INCOME: 'أضف دخل',
  ERROR_VALID_AMOUNT: 'ادخل مبلغ صحيح',
  ERROR_SELECT_CATEGORY: 'اختر فئة',
  ERROR_ENTER_DESCRIPTION: 'ادخل وصف',

  // ─── Dashboard Labels ───────────────────────────────────
  WELCOME_BACK: 'حياك الله',
  CURRENT_BALANCE: 'الرصيد الحالي',
  SPENDING: 'المصاريف',
  TOTAL_ASSETS: 'إجمالي الأصول',
  CASH: 'كاش',
  BANK: 'بنك',
  SAVINGS: 'ادخار',
  CREDIT: 'بطاقة ائتمان',
  UPCOMING_PAYMENTS: 'الدفعات القادمة',
  NO_UPCOMING_SUBS: 'ما فيه اشتراكات قادمة',
  NO_TRANSACTIONS_MONTH: 'ما فيه عمليات هالشهر',
  DUE_THIS_MONTH: 'مستحقة هالشهر',
  RECURRENCE_YEARLY: 'سنوي',
  RECURRENCE_QUARTERLY: 'ربع سنوي',
  RECURRENCE_MONTHLY: 'شهري',
  RECURRENCE_CUSTOM: 'مخصص',
  DUE: 'الاستحقاق',
  OVERDUE: 'متأخر',
  TODAY: 'اليوم',
  TOMORROW: 'بكرة',
  UNCATEGORIZED: 'بدون فئة',

  // ─── Community ──────────────────────────────────────────
  COMMUNITY: 'المجموعات',
  COMMUNITY_SUBTITLE: 'قسّم الفواتير مع ربعك',
  NEW_COMMUNITY: 'مجموعة جديدة',
  COMMUNITY_NAME: 'اسم المجموعة',
  COMMUNITY_NAME_PLACEHOLDER: 'مثلاً: عشاء الشباب، رحلة أبها…',
  CREATE_COMMUNITY: 'إنشاء مجموعة',
  NO_COMMUNITIES: 'ما عندك مجموعات',
  NO_COMMUNITIES_DESC: 'أنشئ مجموعة عشان تقسّم الفواتير\nمع ربعك أو أهلك أو زملائك.',
  MEMBER: 'عضو',
  MEMBERS: 'أعضاء',
  ADMIN: 'مسؤول',
  MEMBER_ROLE: 'عضو',
  ERROR_TITLE: 'خطأ',
  ERROR_CREATE_COMMUNITY: 'ما قدرنا ننشئ المجموعة. حاول مرة ثانية.',
  COULD_NOT_LOAD_COMMUNITIES: 'ما قدرنا نحمّل المجموعات',
  ADD_MEMBER: 'إضافة عضو',
  ADD_MEMBER_SEARCH: 'ابحث بالاسم أو الإيميل...',
  SPLIT_EVENTS: 'فعاليات التقسيم',
  NO_SPLIT_EVENTS: 'ما في فعاليات تقسيم للحين',
  NO_SPLIT_EVENTS_DESC: 'اضغط + عشان تنشئ وحدة وترفق الفاتورة.',
  ADDED_BADGE: 'مضاف',
  NO_USERS_FOUND: 'ما لقينا مستخدمين لـ',
  CREATE_AND_SPLIT: 'إنشاء وتقسيم',

  // ─── SMS Review ─────────────────────────────────────────
  SMS_REVIEW_HEADER: 'مراجعة',
  SMS_ORIGINAL: 'الرسالة الأصلية',
  SMS_BACK: 'رجوع',
  SMS_SKIP: 'تخطي',
  SMS_SAVE_NEXT: 'حفظ والتالي',
  SMS_SAVE_DONE: 'حفظ وانتهاء',
  SMS_SUGGESTED_TEMPLATE: '(مقترح: {name})',

  // ─── AI Insight Card ────────────────────────────────────
  AI_INSIGHT_VIEW_DETAILS: 'عرض التفاصيل',
  AI_INSIGHT_TAP_HINT: 'اضغط للتوسيع · اضغط مطولاً للإخفاء',
  AI_INSIGHT_TYPE_ALERT: '⚠ تنبيه',
  AI_INSIGHT_TYPE_SAVING: '💡 نصيحة توفير',
  AI_INSIGHT_TYPE_TREND: '📈 اتجاه',
  AI_INSIGHT_TYPE_SPENDING: '💸 إنفاق',
  AI_INSIGHT_TYPE_BUDGET: '📊 ميزانية',

  // ─── Benchmark Unlock ───────────────────────────────────
  BENCHMARK_UNLOCK_TITLE: 'شوف وين تقف',
  BENCHMARK_UNLOCK_DESC: 'أضف عمرك ومنطقتك لمقارنة إنفاقك مع مستخدمين مجهولين في SANAD مثلك.',

  // ─── Create Group CTA ───────────────────────────────────
  CREATE_GROUP_ADD_TX_CTA: 'أضف معاملة',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_DELETE_PERMANENTLY: 'حذف نهائي',
  TRASH_DELETE_CONFIRM_SUFFIX: 'بيتحذف نهائياً. متأكد؟',
  ASSET_RESET_FAILED: 'فشل إعادة الضبط',
  UNKNOWN_ERROR: 'خطأ غير معروف',

  // ─── Edit Transaction ───────────────────────────────────
  EDIT_TRANSACTION: 'تعديل المعاملة',
  EXCLUDE_INSIGHTS: 'استبعاد من التحليلات',
  UNCATEGORIZED_COUNT_SUFFIX: 'غير مصنّفة',
  TAP_TO_REVIEW: 'اضغط للمراجعة والتصنيف',
  CHOOSE_GROUP_SPLIT: 'اختر مجموعة للتقسيم',
  SPLITTING: 'جاري التقسيم',
  NEW_GROUP_NAME: 'اسم المجموعة الجديدة',
  NEW_GROUP_PLACEHOLDER: 'مثلاً: عشاء الشلّة',

  // ─── SMS Review ─────────────────────────────────────────
  TRANSACTION_TO_REVIEW: 'عملية تحتاج مراجعة',
  TRANSACTIONS_TO_REVIEW: 'عمليات تحتاج مراجعة',
  MORE: 'المزيد',

  // ─── Account Picker ─────────────────────────────────────
  NO_ACCOUNTS_YET: 'ما عندك حسابات للحين. أضف واحد من الإعدادات.',

  // ─── Common ─────────────────────────────────────────────
  SAVE: 'حفظ',
  DONE: 'تم',
  LOADING: 'جاري التحميل...',
  EXPENSE: 'مصروف',
  INCOME: 'دخل',
  TRANSFER: 'تحويل',

  // ─── Appearance ─────────────────────────────────────────
  APPEARANCE_LIGHT: 'فاتح',
  APPEARANCE_DARK: 'داكن',
  APPEARANCE_SYSTEM: 'تلقائي',

  // ─── Date Range Presets ─────────────────────────────────
  DATE_TODAY: 'اليوم',
  DATE_THIS_WEEK: 'هالأسبوع',
  DATE_THIS_MONTH: 'هالشهر',
  DATE_LAST_MONTH: 'الشهر الماضي',
  DATE_LAST_3_MONTHS: '٣ أشهر',
  DATE_YEAR_TO_DATE: 'من بداية السنة',
  DATE_CUSTOM: 'مخصص',
  DATE_SELECT_RANGE: 'اختر الفترة',
  DATE_FROM: 'من',
  DATE_TO: 'إلى',
  DATE_SELECT: 'اختر',

  // ─── Day Labels (MENA week starts Saturday) ─────────────
  DAY_SA: 'سب',
  DAY_SU: 'أح',
  DAY_MO: 'اث',
  DAY_TU: 'ثل',
  DAY_WE: 'أر',
  DAY_TH: 'خم',
  DAY_FR: 'جم',

  // ─── Day Names ──────────────────────────────────────────
  DAY_SUN: 'أحد',
  DAY_MON: 'اثنين',
  DAY_TUE: 'ثلاثاء',
  DAY_WED: 'أربعاء',
  DAY_THU: 'خميس',
  DAY_FRI: 'جمعة',
  DAY_SAT: 'سبت',

  // ─── Horizon Periods ────────────────────────────────────
  HORIZON_1_MO: 'شهر',
  HORIZON_2_MO: 'شهرين',
  HORIZON_3_MO: '٣ أشهر',
  HORIZON_6_MO: '٦ أشهر',

  // ─── Frequency Labels ───────────────────────────────────
  FREQ_DAILY: 'يومي',
  FREQ_WEEKLY: 'أسبوعي',
  FREQ_BIWEEKLY: 'كل أسبوعين',
  FREQ_MONTHLY: 'شهري',
  FREQ_RECURRING: 'متكرر',

  // ─── Habit Section ──────────────────────────────────────
  HABITS_DETECTED: 'عادات مكتشفة',
  HABIT_SPEND: 'صرف العادات',
  OF_SPENDING: 'من المصاريف',
  SHOW_ALL_HABITS: 'عرض الكل',

  // ─── Subscription Details ───────────────────────────────
  SUBS_DELETE_TITLE: 'حذف',
  SUBS_DELETE_CONFIRM: 'تبي تحذف هالاشتراك؟',
  SUBS_MARK_PAID_TITLE: 'تسجيل دفع',
  SUBS_MARK_PAID_CONFIRM: 'بيتم تحديث موعد الفاتورة الجاية. متأكد؟',
  SUBS_PAID: 'تم الدفع',
  SUBS_PAUSE: 'إيقاف مؤقت',
  SUBS_RESUME: 'استئناف',
  SUBS_MONTHLY_TOTAL: 'المجموع الشهري',
  SUBS_TOTAL_NEXT_1_MO: 'إجمالي الشهر القادم',
  SUBS_TOTAL_NEXT_N_MO: 'إجمالي الـ {n} أشهر القادمة',
  VOICE_RECORDING_TITLE: 'جاري الاستماع…',
  VOICE_RECORDING_SUB: 'تحدث بشكل طبيعي — اضغط إيقاف عند الانتهاء.',
  PROCESSING_AUDIO_TITLE: 'جاري تحويل الصوت إلى نص',
  PROCESSING_AUDIO_SUB: 'نستمع إلى تسجيلك ونكتب ما نسمعه',
  PROCESSING_STAGE_LOAD: 'تحميل الملف',
  PROCESSING_STAGE_CLEAN: 'تنقية الصوت',
  PROCESSING_STAGE_TRANSCRIBE: 'التحويل إلى نص',
  PROCESSING_STAGE_FORMAT: 'تنسيق النتيجة',
  MINIMIZE: 'تصغير',
  MINI_PROCESSING_LABEL: 'جاري معالجة الملاحظة الصوتية…',
  PICK_MONTH: 'اختر الشهر',
  NO_BUDGETS: 'لا توجد ميزانيات بعد',
  HORIZON_CUSTOM: 'مخصص',
  PICK_HORIZON_MONTH: 'حتى',
  SUBS_TOTAL_UNTIL: 'الإجمالي حتى الشهر المحدد',
  SUBS_TOTAL_UNTIL_THIS_MONTH: 'الإجمالي حتى هذا الشهر',
  SUBS_ADD: 'أضف اشتراك',
  SUBS_TRACK_RECURRING_PAYMENTS: 'تتبّع الدفعات المتكررة',
  SUBS_BILLING_MONTHLY: 'شهري',
  SUBS_BILLING_MONTHLY_SHORT: '/شهر',
  SUBS_BILLING_QUARTERLY: 'ربع سنوي',
  SUBS_BILLING_QUARTERLY_SHORT: '/٣ أشهر',
  SUBS_BILLING_YEARLY: 'سنوي',
  SUBS_BILLING_YEARLY_SHORT: '/سنة',

  // ─── Commitment / Due ───────────────────────────────────
  DUE_OVERDUE_DAYS: ' يوم متأخر',
  DUE_TODAY_LABEL: 'مستحق اليوم',
  DUE_TOMORROW_LABEL: 'مستحق بكرة',
  DUE_DAYS_LEFT: ' يوم باقي',

  // ─── Goals ──────────────────────────────────────────────
  GOALS_TITLE: 'الميزانيات والأهداف',
  GOALS_PERIOD: 'الفترة',
  GOALS_PERIOD_WEEKLY: 'أسبوعي',
  GOALS_PERIOD_MONTHLY: 'شهري',
  GOALS_PERIOD_YEARLY: 'سنوي',

  // ─── WhatsApp / SMS Alerts ──────────────────────────────
  ALERT_INVALID_NUMBER: 'رقم غير صحيح',
  ALERT_INVALID_NUMBER_MSG: 'ادخل رقم الواتساب كامل مع رمز الدولة (مثلاً ‎+966512345678‎)',
  ALERT_WHATSAPP_NOT_FOUND: 'الواتساب مو موجود',
  ALERT_WHATSAPP_NOT_FOUND_MSG: 'ثبّت الواتساب عشان تقدر تستخدم هالميزة.',
  ALERT_TEST_FAILED: 'فشل الاختبار',
  ALERT_TEST_FAILED_MSG: 'ما قدرنا نفتح الرابط. تأكد إن التطبيق مثبّت.',
  ALERT_IOS_ONLY: 'آيفون فقط',
  ALERT_IOS_ONLY_MSG: 'الاختصارات التلقائية متوفرة على الآيفون فقط. على الأندرويد، تُقرأ الرسائل تلقائياً بعد الإذن.',

  // ─── Smart Input Alerts ─────────────────────────────────
  ALERT_LIMIT_REACHED: 'وصلت الحد',
  ALERT_PERMISSION_REQUIRED: 'مطلوب إذن',
  ALERT_PERMISSION_MIC: 'نحتاج إذن المايكروفون عشان الإدخال الصوتي.',
  ALERT_PERMISSION_CAMERA: 'نحتاج إذن الكاميرا عشان مسح الفواتير.',
  ALERT_PERMISSION_GALLERY: 'نحتاج إذن المعرض عشان مسح الفواتير.',
  ALERT_FAILED_RECORDING: 'ما قدرنا نبدأ التسجيل. تأكد من إذن المايكروفون.',
  ALERT_FAILED_CAPTURE: 'ما قدرنا نلتقط الصورة',
  ALERT_FAILED_SELECT: 'ما قدرنا نختار الصور',
  SMART_INPUT_AMOUNT_PLACEHOLDER: '٠٫٠٠',
  SMART_INPUT_DESC_PLACEHOLDER: 'وصف العملية',
  SMART_INPUT_MERCHANT_PLACEHOLDER: 'اسم المتجر',
  SMART_INPUT_PERSON_PLACEHOLDER: 'اسم الشخص',
  SMART_INPUT_DATE_PLACEHOLDER: 'سنة-شهر-يوم',
  SMART_INPUT_NOTE_PLACEHOLDER: 'أضف ملاحظة…',
  SMART_INPUT_CAMERA: 'الكاميرا',
  SMART_INPUT_GALLERY: 'المعرض',

  // ─── Review Screen ──────────────────────────────────────
  REVIEW_DONE_VOICE: 'عملية من الصوت.',
  REVIEW_DONE_RECEIPTS: 'عملية من الفواتير.',
  REVIEW_NO_RESULTS: 'ما فيه نتائج',
  REVIEW_NO_RESULTS_MSG: 'ما قدرنا نستخرج مبالغ من الفاتورة.',
  REVIEW_VOICE_FAILED: 'فشل تحويل الصوت',
  REVIEW_RECEIPT_FAILED: 'فشل مسح الفاتورة',
  REVIEW_SCAN_RECEIPT: 'مسح فاتورة',
  REVIEW_CHOOSE_SOURCE: 'اختر المصدر',
  REVIEW_ALL_CAUGHT_UP: 'ما فيه شي للمراجعة!',
  REVIEW_CAMERA_NEEDED: 'نحتاج إذن الكاميرا.',
  REVIEW_GALLERY_NEEDED: 'نحتاج إذن المعرض.',

  // ─── Split Event Alerts ─────────────────────────────────
  SPLIT_OCR_FAILED: 'فشل قراءة الفاتورة',
  SPLIT_OCR_FAILED_MSG: 'ما قدرنا نقرأ الفاتورة. تقدر تضيف الأصناف يدوياً.',
  SPLIT_MISSING_TITLE: 'العنوان مطلوب',
  SPLIT_MISSING_TITLE_MSG: 'ادخل اسم للحدث.',
  SPLIT_NO_ITEMS: 'ما فيه أصناف',
  SPLIT_NO_ITEMS_MSG: 'أضف صنف واحد على الأقل بسعره.',
  SPLIT_ADD_PEOPLE: 'أضف أشخاص',
  SPLIT_ADD_PEOPLE_MSG: 'أضف شخص واحد على الأقل عشان تقسّم معه.',
  SPLIT_CREATE_FAILED: 'ما قدرنا ننشئ التقسيمة. حاول مرة ثانية.',
  SPLIT_CAMERA_NEEDED: 'نحتاج إذن الكاميرا عشان نمسح الفاتورة.',
  SPLIT_SAVE_FAILED: 'ما قدرنا نحفظ التوزيع.',
  SPLIT_SETTLE_FAILED: 'ما قدرنا نحسب التسويات. تأكد إن كل الأصناف موزّعة.',
  SPLIT_NEW: 'تقسيمة جديدة',
  SPLIT_TOTAL: 'المجموع',
  SPLIT_CREATE: 'إنشاء',
  SPLIT_EVENT_NAME: 'اسم الحدث',
  SPLIT_EVENT_PLACEHOLDER: 'مثال: عشاء في كشري التحرير',
  SPLIT_WITH: 'قسّم مع',
  SPLIT_SEARCH_PEOPLE: 'ابحث بالاسم أو الإيميل…',
  SPLIT_SCAN_RECEIPT: 'مسح فاتورة',
  SPLIT_FROM_GALLERY: 'من المعرض',
  SPLIT_ADD_ITEM: 'أضف صنف',
  SPLIT_QTY: 'الكمية',
  SPLIT_PRICE: 'السعر',
  SPLIT_EXTRAS: 'إضافات',

  // ─── Smart Input Card Labels ──────────────────────────────
  SMART_INPUT_SAVED: 'تم الحفظ',
  SMART_INPUT_TRANSACTION_N: 'معاملة',
  SMART_INPUT_LOW_CONFIDENCE: 'دقة متدنّية. تأكّد من التفاصيل.',
  SMART_INPUT_MORE_DETAILS: 'تفاصيل أكثر',
  SMART_INPUT_LESS_DETAILS: 'تفاصيل أقل',
  SMART_INPUT_SELECT_CATEGORY: 'اختر تصنيف عشان تحفظ',
  SMART_INPUT_SAVE_ALL: 'حفظ الكل',
  SMART_INPUT_SCAN_COMPLETE: 'اكتمل المسح',
  SMART_INPUT_SCAN_PROGRESS: 'جاري مسح فاتورة',
  SMART_INPUT_SCAN_OF: 'من',
  SMART_INPUT_SCANNED_OK: 'تم مسحها بنجاح',
  SMART_INPUT_SCANNED_FAILED: 'فشلت',
  SMART_INPUT_INPUT_LABEL: 'المدخل',
  SMART_INPUT_TXN_DETECTED: 'معاملة تم اكتشافها',
  SMART_INPUT_X_SAVED: 'تم حفظها',
  SMART_INPUT_CONFIDENCE_HIGH: 'عالية',
  SMART_INPUT_CONFIDENCE_MEDIUM: 'متوسطة',
  SMART_INPUT_CONFIDENCE_LOW: 'منخفضة',

  // ─── Review Screen Labels ──────────────────────────────────
  REVIEW_TITLE: 'المراجعة',
  REVIEW_NEEDS_ATTENTION: 'تحتاج مراجعتك',
  REVIEW_TRANSACTION_TYPE: 'نوع المعاملة',
  REVIEW_CATEGORY_OPTIONAL: 'التصنيف',
  REVIEW_CONFIRM: 'تأكيد',
  REVIEW_SAVE_UNCATEGORIZED: 'حفظ بدون تصنيف',
  REVIEW_DISCARD_TITLE: 'حذف المعاملة',
  REVIEW_DISCARD_MSG_PREFIX: 'حذف "',
  REVIEW_DISCARD_MSG_SUFFIX: '"؟ ما يمديك ترجعها.',
  REVIEW_NO_MATCH: 'ما لقينا تطابق',
  REVIEW_CATEGORIZED: 'تم تصنيف',
  REVIEW_CREATED: 'تم إنشاء',
  REVIEW_EXISTING: 'موجودة',
  REVIEW_NEW: 'جديدة',
  REVIEW_MATCHED: 'تم مطابقة',
  REVIEW_TAP_STOP: 'اضغط للإيقاف',
  REVIEW_RECORDING: 'جاري التسجيل...',
  REVIEW_VOICE: 'صوت',
  REVIEW_VOICE_HINT: 'قل "#١ بقالة"',
  REVIEW_CAMERA_OR_GALLERY: 'كاميرا أو معرض',
  REVIEW_NO_REVIEW_DESC: 'ما في معاملات تحتاج مراجعة حالياً.',
  REVIEW_SAVE_ALL: 'حفظ الكل',
  REVIEW_SAVE_ALL_READY: 'جاهزة',
  REVIEW_SAVE_ALL_NONE_READY: 'اختر تصنيف للتفعيل',
  REVIEW_SAVE_ALL_PROGRESS: 'جاري الحفظ',
  REVIEW_SAVE_ALL_DONE: 'تم الحفظ',
  REVIEW_SAVE_ALL_FAILED: 'فشل حفظ بعض الصفوف',

  // ─── Split Event Labels ─────────────────────────────────────
  SPLIT_WHO_ORDERED: 'مين طلب:',
  SPLIT_SHARE_HINT: 'اختر كل شخص يشاركك هالصنف. بيتقسم بالتساوي.',
  SPLIT_SAVE_ASSIGNMENT: 'حفظ التوزيع',
  SPLIT_TAP_ASSIGN: 'اضغط للتوزيع',
  SPLIT_COULD_NOT_LOAD: 'ما قدرنا نحمّل الفعالية.',
  SPLIT_SUBTOTAL: 'المجموع الفرعي',
  SPLIT_TAX: 'ضريبة',
  SPLIT_SERVICE_FEE: 'رسوم الخدمة / بقشيش',
  SPLIT_DISCOUNT: 'خصم',
  SPLIT_ITEMS: 'الأصناف',
  SPLIT_UNASSIGNED: 'غير موزّع',
  SPLIT_ASSIGN_MORE: 'وزّع',
  SPLIT_MORE_ITEMS: 'صنف إضافي',
  SPLIT_CALCULATE: 'احسب مين يدفع كم',
  SPLIT_SETTLEMENTS: 'التسويات',
  SPLIT_PAID_COUNT: 'دفعوا',
  SPLIT_EACH_PAYS: 'كل شخص يدفع',
  SPLIT_ITEMS_LABEL: 'أصناف:',
  SPLIT_EXTRAS_LABEL: 'إضافات:',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_TITLE: 'المحذوفات',

  // ─── Month Names ────────────────────────────────────────
  MONTH_JAN: 'يناير',
  MONTH_FEB: 'فبراير',
  MONTH_MAR: 'مارس',
  MONTH_APR: 'أبريل',
  MONTH_MAY: 'مايو',
  MONTH_JUN: 'يونيو',
  MONTH_JUL: 'يوليو',
  MONTH_AUG: 'أغسطس',
  MONTH_SEP: 'سبتمبر',
  MONTH_OCT: 'أكتوبر',
  MONTH_NOV: 'نوفمبر',
  MONTH_DEC: 'ديسمبر',

  // ─── Add Member ─────────────────────────────────────────
  ALERT_ADD_MEMBER_FAILED: 'ما قدرنا نضيف العضو.',

  // ─── SMS Profile Section ────────────────────────────────
  SMS_RECOMMENDED: 'الطريقة المفضلة: اختصارات iOS',
  SMS_ALTERNATIVE: 'بديل: الصق رسالة البنك في الإدخال الذكي',
  SMS_SETUP_GUIDE: 'دليل الإعداد',
  SMS_SHOW_STEPS: 'عرض الخطوات',
  SMS_OPEN_SHORTCUTS: 'افتح تطبيق الاختصارات',
  SMS_TEST_LINK: 'اختبار الرابط',
  SMS_PASTE: 'الصق رسالة',
  SMS_AUTO_IMPORT: 'استيراد رسائل البنك تلقائياً',

  // ─── Subscriptions Screen ───────────────────────────────
  SUBS_NO_YET: 'ما عندك اشتراكات للحين',
  SUBS_NO_YET_DESC: 'أضف اشتراكاتك المتكررة عشان تتابعها.',

  // ─── Profile – WhatsApp ─────────────────────────────────
  WHATSAPP_TITLE: 'ربط الواتساب',
  WHATSAPP_CONNECTED: 'متصل — أرسل مصاريفك عبر الواتساب',
  WHATSAPP_NOT_CONNECTED: 'سجّل مصاريفك عبر الواتساب',
  WHATSAPP_NUMBER_LABEL: 'رقم الواتساب',
  WHATSAPP_DISCONNECT: 'إلغاء الربط',
  WHATSAPP_SAVED: 'تم الحفظ ✓',
  WHATSAPP_CONNECT: 'ربط',
  WHATSAPP_SANDBOX_TITLE: 'الخطوة ٢: انضم للتجربة',
  WHATSAPP_SANDBOX_DESC: 'أرسل كلمة الانضمام لرقم الواتساب عشان نربط الرسائل بحسابك.',
  WHATSAPP_OPEN_JOIN: 'افتح الواتساب وانضم',
  WHATSAPP_USAGE_HINT: 'بعد الانضمام، أرسل مصاريفك لرقم الواتساب:\n"دفعت ١٥٠ ريال كارفور"\n"راتب ٨٠٠٠ ريال وصل"\nبتوصلك رسالة تأكيد وتشوفها في المحفظة.',

  // ─── Profile – SMS Setup ────────────────────────────────
  SMS_SUBTITLE: 'استورد العمليات تلقائياً عبر اختصارات iOS',
  SMS_SHORTCUTS_DESC: 'أنشئ أتمتة تشتغل لما توصلك رسالة من البنك، وترسلها للمحفظة تلقائياً.',
  SMS_PASTE_DESC: 'انسخ أي رسالة بنك والصقها في الإدخال الذكي. المحفظة تستخرج المبلغ والتاجر والنوع.',
  SMS_DEEP_LINK_LABEL: 'رابط الرسائل',
  SMS_COPIED: 'تم النسخ',
  SMS_COPY: 'نسخ',
  SMS_SENT: 'تم الإرسال!',
  SMS_STEP_1_TITLE: 'اضغط على بنك من القائمة فوق',
  SMS_STEP_1_DESC: 'ننسخ لك الشيئين اللي محتاجهم (فلتر المرسل + إجراء Open URL) ونفتح لك تطبيق الاختصارات مباشرة.',
  SMS_STEP_2_TITLE: 'الصق في أتمتة جديدة',
  SMS_STEP_2_DESC: 'في Shortcuts → Automation → Message، الصق اسم المرسل، أضف إجراء "Open URL" والصق الرابط. أوقف "Ask Before Running". خلاص.',
  SMS_STEP_3_TITLE: 'أنشئ أتمتة شخصية',
  SMS_STEP_3_DESC: 'اضغط "+", ثم "Message". حدد المرسل لبنكك (مثلاً "الراجحي", "الأهلي", "stc pay").',
  SMS_STEP_4_TITLE: 'أضف إجراء "فتح رابط"',
  SMS_STEP_4_DESC: 'ابحث عن "Open URL" وأضفه. حط الرابط:\nsanad://sms?text=\nثم اضغط متغير "Shortcut Input" أو "Message" عشان يضيف نص الرسالة.',
  SMS_STEP_5_TITLE: 'عطّل "اسأل قبل التشغيل"',
  SMS_STEP_5_DESC: 'أوقف "Ask Before Running" عشان يشتغل بالخلفية بدون ما يسألك.',
  SMS_STEP_6_TITLE: 'تم!',
  SMS_STEP_6_DESC: 'رسائل البنك الحين بتنشئ عمليات تلقائياً في المحفظة. راجعها في قائمة العمليات.',
  SMS_PRO_TIP: 'نصيحة',
  SMS_PRO_TIP_DESC: 'في الخطوة ٤، بعد ما تلصق الرابط، لازم تضيف نص الرسالة كمتغير. اضغط بعد "text=" وأدرج متغير "Shortcut Input" أو "Message" من قائمة المتغيرات.',
  SMS_FUTURE_NOTE: 'في تحديث قادم بنضيف إجراء "معالجة الرسائل في المحفظة" يظهر مباشرة في الاختصارات — بدون نسخ روابط.',

  // ─── SMS Shortcut Presets ─────────────────────────────────
  SMS_PRESETS_TITLE: 'اختصارات جاهزة للبنوك',
  SMS_PRESETS_SUBTITLE: 'إعداد بنقرة واحدة لبنكك',
  SMS_PRESETS_HINT: 'اضغط "إعداد" — بننسخ اسم المرسل والرابط، ونفتح تطبيق Shortcuts. الصقهم في أتمتة الرسائل وخلاص.',
  SMS_PRESETS_GROUP_SA: 'البنوك السعودية',
  SMS_PRESETS_GROUP_EG: 'البنوك المصرية',
  SMS_PRESET_SENDER: 'المرسل',
  SMS_PRESET_SETUP: 'إعداد',
  SMS_PRESET_READY: 'تم النسخ!',
  SMS_PRESET_TEST: 'تجربة',
  SMS_PRESET_COPIED_TITLE: 'تم نسخ الإعداد',
  SMS_PRESET_COPIED_MSG: 'افتح Shortcuts → Automation → Message. استخدم "{sender}" كمرسل، والصق إجراء Open URL.',

  // ─── Profile – Currency ─────────────────────────────────
  CURRENCY_SAR: 'ريال سعودي',
  CURRENCY_AED: 'درهم إماراتي',
  CURRENCY_EGP: 'جنيه مصري',
  CURRENCY_KWD: 'دينار كويتي',
  CURRENCY_QAR: 'ريال قطري',
  CURRENCY_BHD: 'دينار بحريني',
  CURRENCY_OMR: 'ريال عُماني',
  CURRENCY_JOD: 'دينار أردني',
  CURRENCY_USD: 'دولار أمريكي',
  CURRENCY_EUR: 'يورو',
  CURRENCY_GBP: 'جنيه إسترليني',

  // ─── Profile – Account Types ────────────────────────────
  ACCOUNT_CASH: 'كاش',
  ACCOUNT_BANK: 'حساب بنكي',
  ACCOUNT_SAVINGS: 'توفير',
  ACCOUNT_CREDIT_CARD: 'بطاقة ائتمان',

  // ─── Trash Screen ──────────────────────────────────────
  TRASH_HEADER: 'المحذوفات',
  TRASH_SUBTITLE: 'تنحذف تلقائياً بعد ٧ أيام',
  TRASH_EMPTY_TITLE: 'ما فيه محذوفات',
  TRASH_EMPTY_DESC: 'العمليات والأصول المحذوفة تظهر هنا لمدة ٧ أيام.',

  // ─── Subscriptions Screen Labels ────────────────────────
  SUBS_HEADER: 'الاشتراكات',
  SUBS_TRACK_DESC: 'تابع مدفوعاتك المتكررة',
  SUBS_CHOOSE: 'اختر اشتراك',
  SUBS_DETAILS: 'تفاصيل الاشتراك',
  SUBS_FORM_NAME: 'الاسم',
  SUBS_FORM_AMOUNT: 'المبلغ',
  SUBS_FORM_CYCLE: 'دورة الفوترة',
  SUBS_FORM_NEXT_BILLING: 'تاريخ الفاتورة الجاية',
  SUBS_FORM_DAY: 'اليوم',
  SUBS_FORM_MONTH: 'الشهر',
  SUBS_FORM_YEAR: 'السنة',
  SUBS_FORM_CATEGORY: 'التصنيف',
  SUBS_CUSTOM: 'أضف اشتراك مخصص',
  SUBS_ADD_SUB: 'إضافة اشتراك',
  SUBS_BACK_PRESETS: '→ رجوع للقائمة',
  SUBS_MONTHLY_TOTAL_LABEL: 'المجموع الشهري',
  SUBS_ACTIVE_PAUSED: 'نشط',
  SUBS_PAUSED_LABEL: 'متوقف',
  SUBS_DUE_THIS_MONTH: 'مستحقة هالشهر',
  SUBS_UPCOMING: 'القادمة',
  SUBS_NO_UPCOMING: 'ما فيه مدفوعات قادمة في هالفترة',
  SUBS_PAUSED_SECTION: 'متوقفة',
  SUBS_PLACEHOLDER_NAME: 'مثلاً نتفلكس، نادي، VPN',
  SUBS_PLACEHOLDER_AMOUNT: 'مثلاً ٤٩٫٩٩',
  SUBS_PLACEHOLDER_DAY: 'مثلاً ١',
  SUBS_PLACEHOLDER_MONTH: 'مثلاً ٥',
  SUBS_PLACEHOLDER_YEAR: 'مثلاً ٢٠٢٦',
  SUBS_INVALID_DATE: 'ادخل تاريخ فاتورة صحيح يكون اليوم أو بعده.',

  // ─── Goals Screen Labels ────────────────────────────────
  GOALS_HEADER: 'الأهداف',
  GOALS_SUBTITLE: 'تابع ميزانياتك',
  GOALS_EMPTY_TITLE: 'ما عندك ميزانيات للحين',
  GOALS_EMPTY_DESC: 'أنشئ ميزانية لفئاتك عشان تتابع مصاريفك.',
  GOALS_ON_TRACK_BADGE: 'ماشي',
  GOALS_NEAR_LIMIT_BADGE: 'قريب الحد',
  GOALS_EXCEEDED_BADGE: 'متجاوز',
  GOALS_TOTAL_BUDGETED: 'إجمالي الميزانية',
  GOALS_ACTUAL_SPENT: 'المصروف الفعلي',
  GOALS_YOUR_BUDGETS: 'ميزانياتك',
  GOALS_NEW_BUDGET: 'ميزانية جديدة',
  GOALS_BUDGET_AMOUNT: 'مبلغ الميزانية',
  GOALS_CREATE: 'إنشاء',
  GOALS_CREATING: 'جاري الإنشاء…',
  GOALS_EDIT_BUDGET: 'تعديل الميزانية',
  GOALS_SPENT_OF: 'مصروف من',
  GOALS_DELETE_BUDGET: 'حذف الميزانية',
  GOALS_PLACEHOLDER_AMOUNT: 'مثلاً ٥٠٠',
  GOALS_TRACKED: 'متتبعة',
  GOALS_EXCEEDED_LABEL: 'متجاوزة',

  // ─── Swipeable / TransactionCard ────────────────────────
  ACTION_EDIT: 'تعديل',
  ACTION_SPLIT_BILL: 'تقسيم الحساب',
  ACTION_DELETE: 'حذف',
  DELETE_TRANSACTION: 'حذف العملية',
  DELETE_TRANSACTION_CONFIRM: 'حذف',
  AMOUNT_LABEL: 'المبلغ',

  // ─── Stock Watchlist ────────────────────────────────────
  STOCK_OWNED: 'مملوك',
  STOCK_OWN: 'امتلاك',
  STOCK_CURRENT_PRICE: 'السعر الحالي',
  STOCK_NUM_SHARES: 'عدد الأسهم',
  STOCK_AVG_BUY: 'متوسط سعر الشراء',
  STOCK_DEFAULTS_CURRENT: 'الافتراضي: السعر الحالي',
  STOCK_ESTIMATED_VALUE: 'القيمة التقديرية',
  STOCK_ADDING: 'جاري الإضافة…',
  STOCK_ADD_PORTFOLIO: 'أضف للمحفظة',
  STOCK_ADD: 'إضافة سهم',
  STOCK_SEARCH: 'ابحث عن الأسهم…',
  STOCK_NO_RESULTS: 'ما لقينا أسهم لـ',
  STOCK_REMOVE_TITLE: 'إزالة',
  STOCK_REMOVE_DESC: 'بيتشال من قائمة المتابعة.',
  STOCK_REMOVE: 'إزالة',

  // ─── Payments / Upcoming ────────────────────────────────
  PAYMENTS_IN_NEXT: 'دفعة في الـ',
  MONTH_SINGULAR: 'شهر',
  MONTHS_PLURAL: 'أشهر',

  // ─── Language ───────────────────────────────────────────
  LANG_ENGLISH: 'English',
  LANG_ARABIC: 'العربية',

  // ─── Category Group ─────────────────────────────────────
  CREATE_GROUP_PLACEHOLDER: 'مثلاً عمل جانبي، أطفال، رياضة',
  SUBCATEGORY_PLACEHOLDER: 'اسم الفئة الفرعية',

  // ─── Goal Insights ──────────────────────────────────────
  INSIGHT_EXCEEDED: 'تجاوزت هدف {name} بـ {amount}',
  INSIGHT_NEAR_LIMIT: '{name} وصل إلى {percent}% من الهدف',
  INSIGHT_WITHIN_BUDGET: '{name} ضمن الميزانية',
  INSIGHT_CATEGORIES_ON_TRACK: '{count} فئات ضمن الميزانية',
  GOALS_OVER_BY: 'زيادة بـ {amount}',
  GOALS_REMAINING: 'متبقي {amount}',

  // ─── RTL / Profile / Auth additions ────────────────────────
  FIRST_NAME_LABEL: 'الاسم الأول',
  FIRST_NAME_PLACEHOLDER: 'محمد',
  LAST_NAME_LABEL: 'اسم العائلة',
  LAST_NAME_PLACEHOLDER: 'العلي',
  BIRTHDATE_PLACEHOLDER: 'اختر تاريخ ميلادك',
  AUTH_NO_ACCOUNT: 'ما عندك حساب؟',
  AUTH_SIGN_UP: 'سجّل الحين',
  AUTH_HAVE_ACCOUNT: 'عندك حساب؟',
  AUTH_SIGN_IN_LINK: 'سجّل دخولك',
  AUTH_ERROR_BIRTHDAY_REQUIRED: 'اختر تاريخ ميلادك',
  NEW_GROUP: 'مجموعة جديدة',
  NO_CATEGORIES_AVAILABLE: 'ما فيه فئات',
  EDIT_PROFILE: 'تعديل الملف الشخصي',
  FULL_NAME_AR_HINT: 'اكتب اسمك بالعربي',
  NAME_AR_LABEL: 'الاسم بالعربي',
  NAME_AR_PLACEHOLDER: 'اكتب اسمك بالعربي',
  NAME_AR_SIGNUP_LABEL: 'الاسم بالعربي (اختياري)',
  BIRTHDATE: 'تاريخ الميلاد',
  SAVE_PROFILE: 'حفظ',
  AUTH_SIGN_IN: 'تسجيل دخول',
  AUTH_CREATE_ACCOUNT: 'إنشاء حساب',
  YOU_PAGE_TITLE: 'أنت',
  CONTACT_US: 'تواصل معنا',
  GOAL_SINGULAR: 'هدف',
  ACCOUNT_NAME_PLACEHOLDER: 'اسم الحساب',
  ACCOUNT_BALANCE_PLACEHOLDER: 'الرصيد الافتتاحي (0.00)',
  OF: 'من',
  // ─── Profile sections ───────────────────────────────────────────
  PROFILE_SECTION_PROFILE: 'الملف الشخصي',
  PROFILE_SECTION_AUTOMATION: 'الأتمتة',
  PROFILE_SECTION_DATA: 'البيانات والخصوصية',
  PROFILE_SECTION_ABOUT: 'حول',
  PROFILE_SECTION_ACCOUNT: 'الحساب',
  PROFILE_APP_VERSION: 'الإصدار',
  PROFILE_MANAGE_ACCOUNTS: 'الحسابات والمحافظ',
  PROFILE_WHATSAPP_ROW: 'استيراد واتساب',
  PROFILE_SMS_ROW: 'استيراد رسائل البنك',
  PROFILE_DELETED: 'المحذوفات',
  PROFILE_CONTACT_US: 'الدعم الفني',

  // ─── Profile — WhatsApp Support ─────────────────────────
  SUPPORT_CHAT_TITLE: 'تحتاج مساعدة؟',
  SUPPORT_CHAT_SUBTITLE: 'تواصل معنا على واتساب — اختر موضوعك للبدء',
  SUPPORT_CHAT_BUTTON: 'محادثة عبر واتساب',
  SUPPORT_TOPIC_CATEGORIZE_SMS: 'ساعدني في تصنيف رسائل البنك الأخيرة',
  SUPPORT_TOPIC_ADD_TRANSACTIONS: 'ساعدني في إضافة معاملات',
  SUPPORT_TOPIC_BUDGET: 'ساعدني في إعداد ميزانية',
  SUPPORT_TOPIC_PLAN: 'استفسار عن اشتراكي / الفوترة',
  SUPPORT_TOPIC_OTHER: 'موضوع آخر',

  // ─── Welcome Screen ─────────────────────────────────────
  WELCOME_BRAND: 'SANAD',
  WELCOME_HEADLINE: 'فلوسك،\nبين يديك',
  WELCOME_TAGLINE: 'تابع مصاريفك، حقق أهدافك، واحصل على تحليلات ذكية — مصمم خصيصاً للمنطقة.',
  WELCOME_FEATURE_DASHBOARD_TITLE: 'لوحة ذكية',
  WELCOME_FEATURE_DASHBOARD_DESC: 'رصيدك ودخلك ومصاريفك لحظة بلحظة',
  WELCOME_FEATURE_AI_TITLE: 'مساعد مالي ذكي',
  WELCOME_FEATURE_AI_DESC: 'تحليلات مخصصة من بياناتك',
  WELCOME_FEATURE_SCAN_TITLE: 'مسح الإيصالات ورسائل البنك',
  WELCOME_FEATURE_SCAN_DESC: 'سجّل عملياتك تلقائياً',
  WELCOME_GET_STARTED: 'ابدأ — مجاناً',
  WELCOME_SIGN_IN: 'تسجيل دخول',
  WELCOME_EMAIL_AVAILABLE: 'تسجيل بالإيميل متاح',

  // ─── Forgot Password Extras ─────────────────────────────
  FORGOT_PASSWORD_CHECK_EMAIL: 'راجع إيميلك',
  FORGOT_PASSWORD_CHECK_EMAIL_DESC: 'أرسلنا رابط إعادة تعيين كلمة المرور إلى',
  FORGOT_PASSWORD_SENDING: 'جاري الإرسال…',
  COMMON_BACK_ARROW: '→ رجوع',
  COMMON_BACK: 'رجوع',
  AUTH_BACK_TO_SIGN_IN: 'الرجوع لتسجيل الدخول',

  // ─── Login / Auth Form Extras ───────────────────────────
  AUTH_WELCOME_BACK_HEADLINE: 'حياك الله',
  AUTH_SIGNIN_SUBTITLE: 'سجّل دخولك لمحفظتك',
  AUTH_GET_STARTED_HEADLINE: 'حساب جديد',
  AUTH_SIGNUP_SUBTITLE: 'أنشئ حسابك المجاني',
  AUTH_FORGOT_SHORT: 'نسيت؟',
  AUTH_LABEL_EMAIL: 'الإيميل',
  AUTH_LABEL_PASSWORD: 'كلمة المرور',
  AUTH_LABEL_FIRST_NAME: 'الاسم الأول',
  AUTH_LABEL_LAST_NAME: 'اسم العائلة',
  AUTH_LABEL_BIRTHDAY: 'تاريخ الميلاد',
  AUTH_LABEL_PHONE: 'رقم الجوال',
  AUTH_EMAIL_PLACEHOLDER: 'example@mail.com',
  AUTH_FIRST_NAME_PLACEHOLDER: 'محمد',
  AUTH_LAST_NAME_PLACEHOLDER: 'العلي',
  AUTH_BIRTHDAY_PLACEHOLDER: 'اختر تاريخ ميلادك',
  AUTH_PHONE_PLACEHOLDER: '+966 5X XXX XXXX',
  AUTH_PASSWORD_MIN: 'الحد الأدنى ٨ أحرف',
  AUTH_OR_CONTINUE: 'أو تابع مع',
  AUTH_BIRTHDAY_MODAL_TITLE: 'تاريخ الميلاد',
  AUTH_CONFIRM: 'تأكيد',
  AUTH_LEGAL_PREFIX: 'بالمتابعة، أنت توافق على',
  AUTH_LEGAL_TERMS: 'الشروط',
  AUTH_LEGAL_AND: 'و',
  AUTH_LEGAL_PRIVACY: 'سياسة الخصوصية',

  // ─── Country Names (Onboarding) ─────────────────────────
  COUNTRY_SA: 'السعودية',
  COUNTRY_AE: 'الإمارات',
  COUNTRY_EG: 'مصر',
  COUNTRY_KW: 'الكويت',
  COUNTRY_QA: 'قطر',
  COUNTRY_BH: 'البحرين',
  COUNTRY_OM: 'عُمان',
  COUNTRY_JO: 'الأردن',

  // ─── Profile – Language Alert ───────────────────────────
  LANG_CHANGED_TITLE: 'تم تغيير اللغة',
  LANG_CHANGED_DESC: 'أعد تشغيل التطبيق لتفعيل اللغة الجديدة بالكامل.',

  // ─── Split Event Extras ─────────────────────────────────
  SPLIT_STATUS_SETTLED: 'مسدّد',
  SPLIT_STATUS_OPEN: 'مفتوح',
  SPLIT_ITEM_NAME_PLACEHOLDER: 'اسم العنصر {index}',

  // ─── Trash Extras ───────────────────────────────────────
  TRASH_DELETE_CONFIRM_TEMPLATE: '{label} سيُحذف نهائياً. متابعة؟',

  // ─── Subscription Category Filter Labels ────────────────
  SUB_CAT_STREAMING: 'بث مباشر',
  SUB_CAT_MUSIC: 'موسيقى',
  SUB_CAT_TELECOM: 'اتصالات',
  SUB_CAT_CLOUD: 'سحابي',
  SUB_CAT_PRODUCTIVITY: 'إنتاجية',
  SUB_CAT_GAMING: 'ألعاب',
  SUB_CAT_SHOPPING: 'تسوق',
  SUB_CAT_FITNESS: 'رياضة',
  SUB_CAT_SECURITY: 'أمان',
  SUB_CAT_DELIVERY: 'توصيل',
  SUB_CAT_INSURANCE: 'تأمين',
  SUB_CAT_OTHER: 'أخرى',
} as const;

export type ARStringKey = keyof typeof STRINGS_AR;
