export const STRINGS = {
  // ─── Dashboard ──────────────────────────────────────────
  DASHBOARD_TITLE: 'Dashboard',
  TOTAL_INCOME: 'Total Income',
  TOTAL_SPENT: 'Total Spent',
  NET_BALANCE: 'Net Balance',
  SPENDING_BY_CATEGORY: 'Spending by Category',
  RECENT_TRANSACTIONS: 'Recent Transactions',
  AI_INSIGHTS: 'AI Insight',
  SEE_ALL: 'See All',
  THIS_MONTH: 'This Month',

  // ─── Commitments ────────────────────────────────────────
  COMMITMENTS_THIS_MONTH: "This Month's Commitments",
  COMMITMENTS_NEARLY_DUE: 'Nearly Due',
  COMMITMENTS_UPCOMING: 'Upcoming Next Month',
  NO_COMMITMENTS: 'No commitments yet',
  NO_COMMITMENTS_DESC: 'Add planned expenses like rent, subscriptions, or loan payments.',
  MARK_PAID: 'Paid',

  // ─── Empty States ───────────────────────────────────────
  NO_TRANSACTIONS: 'No transactions yet',
  NO_TRANSACTIONS_DESC: 'Add your first transaction to see your spending overview.',
  NO_INSIGHTS: 'No insights available yet',
  NO_INSIGHTS_DESC: 'Keep tracking your spending to get personalized insights.',

  // ─── Errors ─────────────────────────────────────────────
  ERROR_LOADING_DASHBOARD: 'Failed to load dashboard data',
  ERROR_GENERIC: 'Something went wrong',
  RETRY: 'Retry',

  // ─── Auth ───────────────────────────────────────────────
  LOGIN_TITLE: 'Welcome Back',
  LOGIN_SUBTITLE: 'Sign in to manage your finances',
  REGISTER_TITLE: 'Create Account',
  REGISTER_SUBTITLE: 'Start tracking your spending today',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: '••••••••',
  FULL_NAME_LABEL: 'Full Name',
  FULL_NAME_PLACEHOLDER: 'John Doe',
  LOGIN_BUTTON: 'Sign In',
  REGISTER_BUTTON: 'Create Account',
  LOGIN_LINK: 'Already have an account? Sign in',
  REGISTER_LINK: "Don't have an account? Sign up",
  LOGOUT_BUTTON: 'Sign Out',
  AUTH_ERROR_INVALID_CREDENTIALS: 'Invalid email or password',
  AUTH_ERROR_EMAIL_TAKEN: 'An account with this email already exists',
  AUTH_ERROR_WEAK_PASSWORD: 'Password must be at least 8 characters',
  AUTH_ERROR_INVALID_EMAIL: 'Please enter a valid email address',
  AUTH_ERROR_NAME_REQUIRED: 'Full name is required',

  // ─── Onboarding ────────────────────────────────────────
  ONBOARDING_TITLE: 'Set Up Your Wallet',
  ONBOARDING_SUBTITLE: 'Choose your preferred currency to get started',
  ONBOARDING_CONTINUE: 'Continue',
  ONBOARDING_CURRENCY_LABEL: 'Currency',

  // ─── Profile / Feature Cards ────────────────────────────
  PROFILE_GOALS: 'Goals',
  PROFILE_SUBSCRIPTIONS: 'Subs',
  PROFILE_BILL_SPLIT: 'Split',
  GOALS_ON_TRACK: 'on track',
  GOALS_AT_RISK: 'at risk',
  GOALS_TRACK_BUDGETS: 'Track budgets',
  SUBS_ACTIVE: 'active',
  SUBS_TRACK_RECURRING: 'Track recurring',
  SPLIT_GROUP: 'group',
  SPLIT_GROUPS: 'groups',
  SPLIT_WITH_FRIENDS: 'Split with friends',

  // ─── Settings / Preferences ─────────────────────────────
  SETTINGS_PREFERENCES: 'Preferences',
  SETTINGS_CURRENCY: 'Currency',
  SETTINGS_APPEARANCE: 'Appearance',
  SETTINGS_LANGUAGE: 'Language',
  SETTINGS_ACCOUNTS: 'Accounts',
  SETTINGS_TOTAL_BALANCE: 'Total Balance',
  SETTINGS_ADD_ACCOUNT: 'Add Account',
  SETTINGS_WHATSAPP: 'WhatsApp',
  SETTINGS_SMS_AUTOMATION: 'SMS Automation',
  SETTINGS_TRASH: 'Trash',
  SETTINGS_TRASH_DESC: 'Recover recently deleted items (7 days)',

  // ─── Tabs ───────────────────────────────────────────────
  TAB_HOME: 'Home',
  TAB_TRANSACTIONS: 'Transactions',
  TAB_ANALYTICS: 'Analytics',
  TAB_COINS: 'Coins',
  TAB_PROFILE: 'You',

  // ─── Smart Input ────────────────────────────────────────
  SMART_INPUT_TITLE: 'Smart Input',
  SMART_INPUT_PLACEHOLDER: 'Describe your transaction...',
  SMART_INPUT_PASTE: 'Paste',
  SMART_INPUT_PASTE_DESC: 'SMS / Text',
  SMART_INPUT_VOICE: 'Voice',
  SMART_INPUT_VOICE_DESC: 'Microphone',
  SMART_INPUT_SCAN: 'Scan',
  SMART_INPUT_SCAN_DESC: 'Receipt OCR',
  SMART_INPUT_PARSE: 'Parse',
  SMART_INPUT_STOP: 'Stop',
  SMART_INPUT_RESET: 'Reset',
  SMART_INPUT_PLACEHOLDER_FULL: 'Describe your transaction...\n"Paid 150 EGP at Carrefour"\n"Salary 8000 EGP received"',
  SMART_INPUT_TRANSCRIBING: 'Transcribing voice…',
  SMART_INPUT_TRANSCRIBING_DESC: 'Processing your audio with AI',
  SMART_INPUT_SCANNING_DESC: 'Extracting details from image',
  SMART_INPUT_SUCCESS_ONE: 'Transaction added successfully',
  SMART_INPUT_SUCCESS_MANY: 'transactions added successfully',
  SMART_INPUT_RECORDS_UPDATED: 'Your records have been updated.',
  SMART_INPUT_ADD_ANOTHER: 'Add another transaction',
  SMART_INPUT_VIEW_TRANSACTIONS: 'View transactions',
  SMART_INPUT_BACK_DASHBOARD: 'Back to dashboard',

  // ─── Transaction Filters ────────────────────────────────
  FILTER_ALL: 'All',
  FILTER_EXPENSES: 'Expenses',
  FILTER_INCOME: 'Income',
  FILTER_TRANSFERS: 'Transfers',

  // ─── FeatureGate ────────────────────────────────────────
  FEATURE_AVAILABLE_IN: 'Available in',
  FEATURE_UPGRADE_UNLOCK: 'Upgrade to unlock this feature',
  FEATURE_UPGRADE_TO: 'Upgrade to',

  // ─── Analytics ──────────────────────────────────────────
  ANALYTICS_TITLE: 'Analytics',
  MONEY_ANALYSIS: 'Money Analysis',
  SAVING_TIPS: 'Saving Tips',
  SUBSCRIPTIONS: 'Subscriptions',
  TRANSACTIONS_LABEL: 'Transactions',
  HABITS_LABEL: 'Habits',
  TOP_CATEGORY: 'Top category',
  BUDGETS: 'Budgets',
  ON_TRACK: 'on track',
  AT_RISK: 'at risk',
  SAVED: 'Saved',
  DEFICIT: 'Deficit',
  BUDGET_STATUS: 'Budget Status',
  EXPENSE_TREND: 'Expense Trend',
  SPENDING_HABITS: 'Spending Habits',
  SPENDING_PATTERNS: 'Your Spending Patterns',
  SPENDING_PATTERNS_DESC: 'These patterns appear often in your spending and are worth keeping an eye on.',
  ADD_TXN_ANALYSIS: 'Add transactions to see your spending analysis.',
  NO_DATA_MONTH: 'No data for this month yet.',
  // Saving Tips
  PEERS_SPEND_LESS: 'People your age in your area spend less on',
  PEERS_THAN_YOU: 'than you do.',
  IF_REDUCED_5: 'If reduced by 5%, save',
  PER_MONTH: '/month',
  BIGGEST_SPEND: 'Your biggest spend is',
  SMALL_CUT: '. A small cut here goes a long way.',
  ADD_TXN_TIPS: 'Add transactions to unlock personalized saving tips.',
  NOT_ENOUGH_DATA: 'Not enough data for your age group and area yet.\nCheck back next month.',
  SAVING_OPPORTUNITY: 'SAVING OPPORTUNITY',
  CUT_OVERSPENDING: 'If you cut overspending by 5%, you could save',
  WHERE_SAVE: 'Where You Can Save',
  WHERE_CUT: 'Where You Can Cut Back',
  FIVE_PCT_CUT: '5% cut →',
  COMPARED_MORE: 'Compared to people your age in your area, you spend',
  MORE_ON_THIS: 'on this.',
  MORE_PERCENT: '% more',
  LESS_PERCENT: '% less',
  HOW_COMPARE: 'How You Compare',
  HOW_COMPARE_DESC: 'Compared to people your age and in your region:',
  GREAT_JOB: 'Great job!',
  SPENDING_BELOW: "You're spending at or below what people your age in your area typically spend.",
  YOU: 'You',
  TYPICAL: 'Typical',
  // Subscriptions
  ACTIVE: 'active',
  DUE_THIS_MONTH_SUBS: 'due this month',
  NO_SUBS_YET: 'No subscriptions tracked yet',
  NO_SUBS_ADDED: 'No subscriptions added yet.\nGo to the Subscriptions tab to add them.',
  PER_YEAR: 'Per Year',
  BILLING_SPLIT: 'Billing Split',
  MONTHLY_LABEL: 'Monthly',
  QUARTERLY_LABEL: 'Quarterly',
  YEARLY_LABEL: 'Yearly',
  UPCOMING_BILLING: 'Upcoming Billing',
  IN_DAYS: 'In',
  PAUSED: 'Paused',

  // ─── Assets ─────────────────────────────────────────────
  TOTAL_ASSET_VALUE: 'Total Asset Value',
  GOLD: 'Gold',
  SILVER: 'Silver',
  CRYPTO: 'Crypto',
  STOCKS: 'Stocks',
  TRACK_ASSETS: 'Track Your Assets',
  TRACK_ASSETS_DESC: 'Add gold, silver, or crypto holdings',
  ADD: 'Add',
  ASSETS_TITLE: 'Assets',
  ADD_ASSET: 'Add Asset',
  ASSET_TYPE: 'Asset Type',
  UNIT: 'Unit',
  QUANTITY: 'Quantity',
  AVG_BUY_PRICE: 'Average Buy Price',
  OPTIONAL_PER: 'optional, per',
  SAVE_CHANGES: 'Save Changes',
  DELETE_ASSET: 'Delete Asset',
  DELETE_ASSET_CONFIRM: 'Remove from your portfolio?',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  INSIGHTS: 'Insights',
  CURRENT_PRICE: 'Current price',
  CURRENT_VALUE: 'Current Value',
  LEAVE_EMPTY_REMOVE: 'Leave empty to remove',
  FAILED_LOAD_ASSETS: 'Failed to load assets',
  INSIGHT_GOLD_HEAVY: 'Your portfolio is heavily concentrated in gold. Consider diversifying into other asset classes.',
  INSIGHT_CRYPTO_HEAVY: 'Crypto makes up most of your portfolio. This is a volatile asset — consider balancing with stable assets like gold.',
  INSIGHT_STOCK_HEAVY: 'Stocks are most of your allocation right now. Keep an eye on sector concentration risk.',
  INSIGHT_DIVERSIFIED: 'Good diversification! You have exposure across metals, crypto, and stocks.',
  INSIGHT_PORTFOLIO_UP: 'Your portfolio is up',
  INSIGHT_PORTFOLIO_DOWN: 'Your portfolio is down',
  INSIGHT_FROM_BUY: 'from your buy prices.',
  INSIGHT_HOLD_STEADY: 'from your buy prices. Hold steady — markets fluctuate.',
  INSIGHT_ADD_BUY_PRICE: 'Add buy prices to',
  INSIGHT_TRACK_GAINS: 'to track gains/losses.',

  // ─── Add Transaction ────────────────────────────────────
  ADD_TRANSACTION: 'Add Transaction',
  AMOUNT: 'Amount',
  DESCRIPTION: 'Description',
  DESCRIPTION_PLACEHOLDER: 'e.g. Grocery shopping',
  CATEGORY: 'Category',
  ACCOUNT: 'Account',
  ACCOUNT_OPTIONAL: '(optional)',
  DATE: 'Date',
  NOTES_OPTIONAL: 'Notes (optional)',
  NOTE_PLACEHOLDER: 'Add a note…',
  SAVING: 'Saving…',
  ADD_EXPENSE: 'Add Expense',
  ADD_INCOME: 'Add Income',
  ERROR_VALID_AMOUNT: 'Enter a valid amount',
  ERROR_SELECT_CATEGORY: 'Select a category',
  ERROR_ENTER_DESCRIPTION: 'Enter a description',

  // ─── Dashboard Labels ───────────────────────────────────
  WELCOME_BACK: 'Welcome Back',
  CURRENT_BALANCE: 'Current Balance',
  SPENDING: 'Spending',
  TOTAL_ASSETS: 'Total Assets',
  CASH: 'Cash',
  BANK: 'Bank',
  SAVINGS: 'Savings',
  CREDIT: 'Credit',
  UPCOMING_PAYMENTS: 'Upcoming Payments',
  NO_UPCOMING_SUBS: 'No upcoming subscription payments',
  NO_TRANSACTIONS_MONTH: 'No transactions this month',
  DUE_THIS_MONTH: 'due this month',
  RECURRENCE_YEARLY: 'Yearly',
  RECURRENCE_QUARTERLY: 'Quarterly',
  RECURRENCE_MONTHLY: 'Monthly',
  RECURRENCE_CUSTOM: 'Custom',
  DUE: 'Due',
  OVERDUE: 'Overdue',
  TODAY: 'Today',
  TOMORROW: 'Tomorrow',
  UNCATEGORIZED: 'Uncategorized',

  // ─── Community ──────────────────────────────────────────
  COMMUNITY: 'Community',
  COMMUNITY_SUBTITLE: 'Split bills with your group',
  NEW_COMMUNITY: 'New Community',
  COMMUNITY_NAME: 'Community Name',
  COMMUNITY_NAME_PLACEHOLDER: 'e.g. Dinner Group, Trip to Hurghada…',
  CREATE_COMMUNITY: 'Create Community',
  NO_COMMUNITIES: 'No Communities',
  NO_COMMUNITIES_DESC: 'Create a group to split bills with\nfriends, family or colleagues.',
  MEMBER: 'member',
  MEMBERS: 'members',
  ADMIN: 'Admin',
  MEMBER_ROLE: 'Member',
  ERROR_TITLE: 'Error',
  ERROR_CREATE_COMMUNITY: 'Could not create community. Please try again.',
  COULD_NOT_LOAD_COMMUNITIES: 'Could not load communities',
  ADD_MEMBER: 'Add Member',
  ADD_MEMBER_SEARCH: 'Search by name or email...',
  SPLIT_EVENTS: 'Split Events',
  NO_SPLIT_EVENTS: 'No split events yet',
  NO_SPLIT_EVENTS_DESC: 'Tap + to create one and attach a receipt.',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_DELETE_PERMANENTLY: 'Delete Permanently',
  TRASH_DELETE_CONFIRM_SUFFIX: 'will be gone forever. Continue?',
  ASSET_RESET_FAILED: 'Reset failed',
  UNKNOWN_ERROR: 'Unknown error',

  // ─── Edit Transaction ───────────────────────────────────
  EDIT_TRANSACTION: 'Edit Transaction',
  EXCLUDE_INSIGHTS: 'Exclude from insights',
  UNCATEGORIZED_COUNT_SUFFIX: 'uncategorized',
  TAP_TO_REVIEW: 'Tap to review and categorize',
  CHOOSE_GROUP_SPLIT: 'Choose Group to Split',
  SPLITTING: 'Splitting',
  NEW_GROUP_NAME: 'New Group Name',
  NEW_GROUP_PLACEHOLDER: 'e.g. Dinner Group',

  // ─── SMS Review ─────────────────────────────────────────
  TRANSACTION_TO_REVIEW: 'transaction to review',
  TRANSACTIONS_TO_REVIEW: 'transactions to review',
  MORE: 'more',

  // ─── Account Picker ─────────────────────────────────────
  NO_ACCOUNTS_YET: 'No accounts yet. Add one in Settings.',

  // ─── Common ─────────────────────────────────────────────
  SAVE: 'Save',
  DONE: 'Done',
  LOADING: 'Loading...',
  EXPENSE: 'Expense',
  INCOME: 'Income',
  TRANSFER: 'Transfer',

  // ─── Appearance ─────────────────────────────────────────
  APPEARANCE_LIGHT: 'Light',
  APPEARANCE_DARK: 'Dark',
  APPEARANCE_SYSTEM: 'System',

  // ─── Date Range Presets ─────────────────────────────────
  DATE_TODAY: 'Today',
  DATE_THIS_WEEK: 'This Week',
  DATE_THIS_MONTH: 'This Month',
  DATE_LAST_MONTH: 'Last Month',
  DATE_LAST_3_MONTHS: 'Last 3 Mo',
  DATE_YEAR_TO_DATE: 'YTD',
  DATE_CUSTOM: 'Custom',
  DATE_SELECT_RANGE: 'Select Date Range',
  DATE_FROM: 'From',
  DATE_TO: 'To',
  DATE_SELECT: 'Select',

  // ─── Day Labels (MENA week starts Saturday) ─────────────
  DAY_SA: 'Sa',
  DAY_SU: 'Su',
  DAY_MO: 'Mo',
  DAY_TU: 'Tu',
  DAY_WE: 'We',
  DAY_TH: 'Th',
  DAY_FR: 'Fr',

  // ─── Day Names ──────────────────────────────────────────
  DAY_SUN: 'Sun',
  DAY_MON: 'Mon',
  DAY_TUE: 'Tue',
  DAY_WED: 'Wed',
  DAY_THU: 'Thu',
  DAY_FRI: 'Fri',
  DAY_SAT: 'Sat',

  // ─── Horizon Periods ────────────────────────────────────
  HORIZON_1_MO: '1 mo',
  HORIZON_2_MO: '2 mo',
  HORIZON_3_MO: '3 mo',
  HORIZON_6_MO: '6 mo',

  // ─── Frequency Labels ───────────────────────────────────
  FREQ_DAILY: 'Daily',
  FREQ_WEEKLY: 'Weekly',
  FREQ_BIWEEKLY: 'Bi-weekly',
  FREQ_MONTHLY: 'Monthly',
  FREQ_RECURRING: 'Recurring',

  // ─── Habit Section ──────────────────────────────────────
  HABITS_DETECTED: 'Habits detected',
  HABIT_SPEND: 'Habit spend',
  OF_SPENDING: 'Of spending',
  SHOW_ALL_HABITS: 'Show all',
  SHOW_LESS: 'Show less',

  // ─── Subscription Details ───────────────────────────────
  SUBS_DELETE_TITLE: 'Delete',
  SUBS_DELETE_CONFIRM: 'Remove this subscription?',
  SUBS_MARK_PAID_TITLE: 'Mark as Paid',
  SUBS_MARK_PAID_CONFIRM: 'This will advance the next billing date. Continue?',
  SUBS_PAID: 'Paid',
  SUBS_PAUSE: 'Pause',
  SUBS_RESUME: 'Resume',
  SUBS_MONTHLY_TOTAL: 'Monthly Total',
  SUBS_ADD: 'Add Subscription',
  SUBS_TRACK_RECURRING_PAYMENTS: 'Track your recurring payments',
  SUBS_BILLING_MONTHLY: 'Monthly',
  SUBS_BILLING_MONTHLY_SHORT: '/mo',
  SUBS_BILLING_QUARTERLY: 'Quarterly',
  SUBS_BILLING_QUARTERLY_SHORT: '/3mo',
  SUBS_BILLING_YEARLY: 'Yearly',
  SUBS_BILLING_YEARLY_SHORT: '/yr',

  // ─── Commitment / Due ───────────────────────────────────
  DUE_OVERDUE_DAYS: 'd overdue',
  DUE_TODAY_LABEL: 'Due today',
  DUE_TOMORROW_LABEL: 'Due tomorrow',
  DUE_DAYS_LEFT: 'd left',

  // ─── Goals ──────────────────────────────────────────────
  GOALS_TITLE: 'Budget Goals',
  GOALS_PERIOD: 'Period',
  GOALS_PERIOD_WEEKLY: 'Weekly',
  GOALS_PERIOD_MONTHLY: 'Monthly',
  GOALS_PERIOD_YEARLY: 'Yearly',

  // ─── WhatsApp / SMS Alerts ──────────────────────────────
  ALERT_INVALID_NUMBER: 'Invalid number',
  ALERT_INVALID_NUMBER_MSG: 'Enter your full WhatsApp number with country code (e.g. +966512345678)',
  ALERT_WHATSAPP_NOT_FOUND: 'WhatsApp not found',
  ALERT_WHATSAPP_NOT_FOUND_MSG: 'Please install WhatsApp to use this feature.',
  ALERT_TEST_FAILED: 'Test Failed',
  ALERT_TEST_FAILED_MSG: 'Could not open the deep link. Make sure the app is installed.',
  ALERT_IOS_ONLY: 'iOS Only',
  ALERT_IOS_ONLY_MSG: 'Shortcuts automation is available on iPhone only. On Android, SMS is read automatically when permission is granted.',

  // ─── Smart Input Alerts ─────────────────────────────────
  ALERT_LIMIT_REACHED: 'Limit Reached',
  ALERT_PERMISSION_REQUIRED: 'Permission Required',
  ALERT_PERMISSION_MIC: 'Microphone permission is needed for voice input.',
  ALERT_PERMISSION_CAMERA: 'Camera permission is needed for receipt scanning.',
  ALERT_PERMISSION_GALLERY: 'Gallery permission is needed for receipt scanning.',
  ALERT_FAILED_RECORDING: 'Failed to start recording. Please check microphone permissions.',
  ALERT_FAILED_CAPTURE: 'Failed to capture image',
  ALERT_FAILED_SELECT: 'Failed to select images',
  SMART_INPUT_AMOUNT_PLACEHOLDER: '0.00',
  SMART_INPUT_DESC_PLACEHOLDER: 'Transaction description',
  SMART_INPUT_MERCHANT_PLACEHOLDER: 'Merchant name',
  SMART_INPUT_PERSON_PLACEHOLDER: 'Person name',
  SMART_INPUT_DATE_PLACEHOLDER: 'YYYY-MM-DD',
  SMART_INPUT_NOTE_PLACEHOLDER: 'Add a note…',
  SMART_INPUT_CAMERA: 'Camera',
  SMART_INPUT_GALLERY: 'Gallery',

  // ─── Review Screen ──────────────────────────────────────
  REVIEW_DONE_VOICE: 'transaction(s) from voice.',
  REVIEW_DONE_RECEIPTS: 'transaction(s) from receipts.',
  REVIEW_NO_RESULTS: 'No Results',
  REVIEW_NO_RESULTS_MSG: 'Could not extract amounts from the receipt(s).',
  REVIEW_VOICE_FAILED: 'Voice transcription failed',
  REVIEW_RECEIPT_FAILED: 'Receipt scanning failed',
  REVIEW_SCAN_RECEIPT: 'Scan Receipt',
  REVIEW_CHOOSE_SOURCE: 'Choose a source',
  REVIEW_ALL_CAUGHT_UP: 'All caught up!',
  REVIEW_CAMERA_NEEDED: 'Camera permission needed.',
  REVIEW_GALLERY_NEEDED: 'Gallery permission needed.',

  // ─── Split Event Alerts ─────────────────────────────────
  SPLIT_OCR_FAILED: 'OCR Failed',
  SPLIT_OCR_FAILED_MSG: 'Could not read the receipt. You can fill in items manually.',
  SPLIT_MISSING_TITLE: 'Missing Title',
  SPLIT_MISSING_TITLE_MSG: 'Please enter a name for this event.',
  SPLIT_NO_ITEMS: 'No Items',
  SPLIT_NO_ITEMS_MSG: 'Please add at least one item with a price.',
  SPLIT_ADD_PEOPLE: 'Add People',
  SPLIT_ADD_PEOPLE_MSG: 'Add at least one person to split with.',
  SPLIT_CREATE_FAILED: 'Could not create split event. Please try again.',
  SPLIT_CAMERA_NEEDED: 'Camera access is needed to scan receipts.',
  SPLIT_SAVE_FAILED: 'Could not save assignments.',
  SPLIT_SETTLE_FAILED: 'Could not compute settlements. Make sure all items are assigned.',
  SPLIT_NEW: 'New Split',
  SPLIT_TOTAL: 'Total',

  // ─── Smart Input Card Labels ──────────────────────────────
  SMART_INPUT_SAVED: 'Saved',
  SMART_INPUT_TRANSACTION_N: 'Transaction',
  SMART_INPUT_LOW_CONFIDENCE: 'Low confidence. Please verify the details.',
  SMART_INPUT_MORE_DETAILS: 'More details',
  SMART_INPUT_LESS_DETAILS: 'Less details',
  SMART_INPUT_SELECT_CATEGORY: 'Select a category to save',
  SMART_INPUT_SAVE_ALL: 'Save All',
  SMART_INPUT_SCAN_COMPLETE: 'Scan Complete',
  SMART_INPUT_SCAN_PROGRESS: 'Scanning receipt',
  SMART_INPUT_SCAN_OF: 'of',
  SMART_INPUT_SCANNED_OK: 'scanned successfully',
  SMART_INPUT_SCANNED_FAILED: 'failed',
  SMART_INPUT_INPUT_LABEL: 'Input',
  SMART_INPUT_TXN_DETECTED: 'transactions detected',
  SMART_INPUT_X_SAVED: 'saved',
  SMART_INPUT_CONFIDENCE_HIGH: 'High',
  SMART_INPUT_CONFIDENCE_MEDIUM: 'Medium',
  SMART_INPUT_CONFIDENCE_LOW: 'Low',

  // ─── Review Screen Labels ──────────────────────────────────
  REVIEW_TITLE: 'Review',
  REVIEW_NEEDS_ATTENTION: 'need your attention',
  REVIEW_TRANSACTION_TYPE: 'Transaction Type',
  REVIEW_CATEGORY_OPTIONAL: 'Category',
  REVIEW_CONFIRM: 'Confirm',
  REVIEW_SAVE_UNCATEGORIZED: 'Save Uncategorized',
  REVIEW_DISCARD_TITLE: 'Discard Transaction',
  REVIEW_DISCARD_MSG_PREFIX: 'Delete "',
  REVIEW_DISCARD_MSG_SUFFIX: '"? This cannot be undone.',
  REVIEW_NO_MATCH: 'No Match',
  REVIEW_CATEGORIZED: 'Categorized',
  REVIEW_CREATED: 'Created',
  REVIEW_EXISTING: 'existing',
  REVIEW_NEW: 'new',
  REVIEW_MATCHED: 'Matched',
  REVIEW_TAP_STOP: 'Tap to Stop',
  REVIEW_RECORDING: 'Recording...',
  REVIEW_VOICE: 'Voice',
  REVIEW_VOICE_HINT: 'Say "#1 is groceries"',
  REVIEW_CAMERA_OR_GALLERY: 'Camera or gallery',
  REVIEW_NO_REVIEW_DESC: 'No transactions need review right now.',

  // ─── Split Event Labels ─────────────────────────────────────
  SPLIT_WHO_ORDERED: 'Who ordered:',
  SPLIT_SHARE_HINT: 'Select everyone who shares this item. It will be split equally.',
  SPLIT_SAVE_ASSIGNMENT: 'Save Assignment',
  SPLIT_TAP_ASSIGN: 'Tap to assign',
  SPLIT_COULD_NOT_LOAD: 'Could not load event.',
  SPLIT_SUBTOTAL: 'Subtotal',
  SPLIT_TAX: 'Tax',
  SPLIT_SERVICE_FEE: 'Service Fee',
  SPLIT_DISCOUNT: 'Discount',
  SPLIT_ITEMS: 'ITEMS',
  SPLIT_UNASSIGNED: 'unassigned',
  SPLIT_ASSIGN_MORE: 'Assign',
  SPLIT_MORE_ITEMS: 'more item(s)',
  SPLIT_CALCULATE: 'Calculate Who Owes What',
  SPLIT_SETTLEMENTS: 'SETTLEMENTS',
  SPLIT_PAID_COUNT: 'paid',
  SPLIT_EACH_PAYS: 'Each person pays',
  SPLIT_ITEMS_LABEL: 'Items:',
  SPLIT_EXTRAS_LABEL: 'Extras:',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_TITLE: 'Trash',

  // ─── Month Names (for localized date display) ───────────
  MONTH_JAN: 'January',
  MONTH_FEB: 'February',
  MONTH_MAR: 'March',
  MONTH_APR: 'April',
  MONTH_MAY: 'May',
  MONTH_JUN: 'June',
  MONTH_JUL: 'July',
  MONTH_AUG: 'August',
  MONTH_SEP: 'September',
  MONTH_OCT: 'October',
  MONTH_NOV: 'November',
  MONTH_DEC: 'December',

  // ─── Add Member ─────────────────────────────────────────
  ALERT_ADD_MEMBER_FAILED: 'Could not add member.',

  // ─── SMS Profile Section ────────────────────────────────
  SMS_RECOMMENDED: 'Recommended: iOS Shortcuts',
  SMS_ALTERNATIVE: 'Alternative: Paste SMS in Smart Input',
  SMS_SETUP_GUIDE: 'Setup guide',
  SMS_SHOW_STEPS: 'Show steps',
  SMS_OPEN_SHORTCUTS: 'Open Shortcuts App',
  SMS_TEST_LINK: 'Test Link',
  SMS_PASTE: 'Paste SMS',
  SMS_AUTO_IMPORT: 'Auto-import bank SMS',

  // ─── Subscriptions Screen ───────────────────────────────
  SUBS_NO_YET: 'No subscriptions yet',
  SUBS_NO_YET_DESC: 'Add your recurring payments to track them.',

  // ─── Profile – WhatsApp ─────────────────────────────────
  WHATSAPP_TITLE: 'WhatsApp Integration',
  WHATSAPP_CONNECTED: 'Connected — send expenses via WhatsApp',
  WHATSAPP_NOT_CONNECTED: 'Log expenses by texting on WhatsApp',
  WHATSAPP_NUMBER_LABEL: 'Your WhatsApp number',
  WHATSAPP_DISCONNECT: 'Disconnect',
  WHATSAPP_SAVED: 'Saved ✓',
  WHATSAPP_CONNECT: 'Connect',
  WHATSAPP_SANDBOX_TITLE: 'Step 2: Join the Sandbox',
  WHATSAPP_SANDBOX_DESC: 'Send the join keyword to our WhatsApp number so messages get routed to your account.',
  WHATSAPP_OPEN_JOIN: 'Open WhatsApp & Join',
  WHATSAPP_USAGE_HINT: 'After joining, text your expenses to the WhatsApp number:\n"Paid 150 EGP at Carrefour"\n"دفعت ٢٠٠ جنيه كارفور"\nYou\'ll get a confirmation reply and see it in your Wallet app.',

  // ─── Profile – SMS Setup ────────────────────────────────
  SMS_SUBTITLE: 'Capture transactions automatically via iOS Shortcuts',
  SMS_SHORTCUTS_DESC: 'Create an automation that triggers when you receive a bank SMS, and sends it to Wallet automatically.',
  SMS_PASTE_DESC: 'Copy any bank SMS and paste it in Smart Input. Wallet parses amount, merchant, and type.',
  SMS_DEEP_LINK_LABEL: 'Your SMS deep link',
  SMS_COPIED: 'Copied',
  SMS_COPY: 'Copy',
  SMS_SENT: 'Sent!',
  SMS_STEP_1_TITLE: 'Open the Shortcuts app',
  SMS_STEP_1_DESC: 'Find it on your home screen, or search for \'Shortcuts\' in Spotlight.',
  SMS_STEP_2_TITLE: 'Go to Automation tab',
  SMS_STEP_2_DESC: 'Tap the Automation tab at the bottom of the Shortcuts app.',
  SMS_STEP_3_TITLE: 'Create Personal Automation',
  SMS_STEP_3_DESC: 'Tap "+", then "Message". Set the sender to your bank (e.g. "CIB", "NBE", "QNB").',
  SMS_STEP_4_TITLE: 'Add "Open URL" action',
  SMS_STEP_4_DESC: 'Search for "Open URL" and add it. Set the URL to:\nwalletapp://sms?text=\nThen tap "Shortcut Input" or "Message" variable to append the SMS body.',
  SMS_STEP_5_TITLE: 'Disable \'Ask Before Running\'',
  SMS_STEP_5_DESC: 'Toggle off \'Ask Before Running\' so it processes silently in the background.',
  SMS_STEP_6_TITLE: 'Done!',
  SMS_STEP_6_DESC: 'Bank SMS will now auto-create transactions in Wallet. Check the transactions list for review.',
  SMS_PRO_TIP: 'Pro tip',
  SMS_PRO_TIP_DESC: 'In Step 4, after pasting the deep link URL, you need to add the message body as a variable. Tap after the "text=" part, then insert the "Shortcut Input" or "Message" variable from the magic variable list.',
  SMS_FUTURE_NOTE: 'A future update will add a native "Process SMS in Wallet" action that appears directly in the Shortcuts app — no URL copy needed.',

  // ─── Profile – Currency ─────────────────────────────────
  CURRENCY_SAR: 'Saudi Riyal',
  CURRENCY_AED: 'UAE Dirham',
  CURRENCY_EGP: 'Egyptian Pound',
  CURRENCY_KWD: 'Kuwaiti Dinar',
  CURRENCY_QAR: 'Qatari Riyal',
  CURRENCY_BHD: 'Bahraini Dinar',
  CURRENCY_OMR: 'Omani Rial',
  CURRENCY_JOD: 'Jordanian Dinar',
  CURRENCY_USD: 'US Dollar',
  CURRENCY_EUR: 'Euro',
  CURRENCY_GBP: 'British Pound',

  // ─── Profile – Account Types ────────────────────────────
  ACCOUNT_CASH: 'Cash',
  ACCOUNT_BANK: 'Bank Account',
  ACCOUNT_SAVINGS: 'Savings',
  ACCOUNT_CREDIT_CARD: 'Credit Card',

  // ─── Trash Screen ──────────────────────────────────────
  TRASH_HEADER: 'Trash',
  TRASH_SUBTITLE: 'Items auto-delete after 7 days',
  TRASH_EMPTY_TITLE: 'Trash is empty',
  TRASH_EMPTY_DESC: 'Deleted transactions and assets appear here for 7 days.',

  // ─── Subscriptions Screen Labels ────────────────────────
  SUBS_HEADER: 'Subscriptions',
  SUBS_TRACK_DESC: 'Track your recurring payments',
  SUBS_CHOOSE: 'Choose Subscription',
  SUBS_DETAILS: 'Subscription Details',
  SUBS_FORM_NAME: 'Name',
  SUBS_FORM_AMOUNT: 'Amount',
  SUBS_FORM_CYCLE: 'Billing Cycle',
  SUBS_FORM_DAY: 'Billing Day (1–31)',
  SUBS_FORM_CATEGORY: 'Category',
  SUBS_CUSTOM: 'Add Custom Subscription',
  SUBS_ADD_SUB: 'Add Subscription',
  SUBS_BACK_PRESETS: '← Back to presets',
  SUBS_MONTHLY_TOTAL_LABEL: 'Monthly Total',
  SUBS_ACTIVE_PAUSED: 'active',
  SUBS_PAUSED_LABEL: 'paused',
  SUBS_DUE_THIS_MONTH: 'Due This Month',
  SUBS_UPCOMING: 'Upcoming',
  SUBS_NO_UPCOMING: 'No upcoming payments in this period',
  SUBS_PAUSED_SECTION: 'Paused',
  SUBS_PLACEHOLDER_NAME: 'e.g. Netflix, Gym, VPN',
  SUBS_PLACEHOLDER_AMOUNT: 'e.g. 49.99',
  SUBS_PLACEHOLDER_DAY: 'e.g. 1',

  // ─── Goals Screen Labels ────────────────────────────────
  GOALS_HEADER: 'Goals',
  GOALS_SUBTITLE: 'Track your budget targets',
  GOALS_EMPTY_TITLE: 'No budget goals yet',
  GOALS_EMPTY_DESC: 'Create budgets for your categories to start tracking spending goals.',
  GOALS_ON_TRACK_BADGE: 'On Track',
  GOALS_NEAR_LIMIT_BADGE: 'Near Limit',
  GOALS_EXCEEDED_BADGE: 'Exceeded',
  GOALS_TOTAL_BUDGETED: 'Total Budgeted',
  GOALS_ACTUAL_SPENT: 'Actual Spent',
  GOALS_YOUR_BUDGETS: 'Your Budgets',
  GOALS_NEW_BUDGET: 'New Budget Goal',
  GOALS_BUDGET_AMOUNT: 'Budget Amount',
  GOALS_CREATE: 'Create Goal',
  GOALS_CREATING: 'Creating…',
  GOALS_EDIT_BUDGET: 'Edit Budget',
  GOALS_SPENT_OF: 'spent of',
  GOALS_DELETE_BUDGET: 'Delete Budget',
  GOALS_PLACEHOLDER_AMOUNT: 'e.g. 500',
  GOALS_TRACKED: 'tracked',
  GOALS_EXCEEDED_LABEL: 'exceeded',

  // ─── Swipeable / TransactionCard ────────────────────────
  ACTION_EDIT: 'Edit',
  ACTION_SPLIT_BILL: 'Split Bill',
  ACTION_DELETE: 'Delete',
  DELETE_TRANSACTION: 'Delete Transaction',
  DELETE_TRANSACTION_CONFIRM: 'Delete',
  AMOUNT_LABEL: 'Amount',

  // ─── Stock Watchlist ────────────────────────────────────
  STOCK_OWNED: 'OWNED',
  STOCK_OWN: 'Own',
  STOCK_CURRENT_PRICE: 'Current price',
  STOCK_NUM_SHARES: 'Number of Shares',
  STOCK_AVG_BUY: 'Average Buy Price',
  STOCK_DEFAULTS_CURRENT: 'defaults to current',
  STOCK_ESTIMATED_VALUE: 'Estimated Value',
  STOCK_ADDING: 'Adding...',
  STOCK_ADD_PORTFOLIO: 'Add to Portfolio',
  STOCK_ADD: 'Add Stock',
  STOCK_SEARCH: 'Search stocks...',
  STOCK_NO_RESULTS: 'No stocks found for',
  STOCK_REMOVE_TITLE: 'Remove',
  STOCK_REMOVE_DESC: 'will be removed from your watchlist.',
  STOCK_REMOVE: 'Remove',

  // ─── Payments / Upcoming ────────────────────────────────
  PAYMENTS_IN_NEXT: 'payment(s) in next',
  MONTH_SINGULAR: 'month',
  MONTHS_PLURAL: 'months',

  // ─── Language ───────────────────────────────────────────
  LANG_ENGLISH: 'English',
  LANG_ARABIC: 'العربية',

  // ─── Category Group ─────────────────────────────────────
  CREATE_GROUP_PLACEHOLDER: 'e.g. Side Hustle, Kids, Fitness',
  SUBCATEGORY_PLACEHOLDER: 'Subcategory name',
} as const;
