export const STRINGS = {
  // ─── Dashboard ──────────────────────────────────────────
  DASHBOARD_TITLE: 'Dashboard',
  TOTAL_INCOME: 'Total Income',
  TOTAL_SPENT: 'Total Spent',
  NET_BALANCE: 'Net Balance',
  SPENDING_BY_CATEGORY: 'Spending by Category',
  RECENT_TRANSACTIONS: 'Recent Transactions',
  AI_INSIGHTS: 'AI Insight',
  SEE_ALL: 'See All',
  THIS_MONTH: 'This Month',

  // ─── Commitments ────────────────────────────────────────
  COMMITMENTS_THIS_MONTH: "This Month's Commitments",
  COMMITMENTS_NEARLY_DUE: 'Nearly Due',
  COMMITMENTS_UPCOMING: 'Upcoming Next Month',
  NO_COMMITMENTS: 'No commitments yet',
  NO_COMMITMENTS_DESC: 'Add planned expenses like rent, subscriptions, or loan payments.',
  MARK_PAID: 'Paid',

  // ─── Empty States ───────────────────────────────────────
  NO_TRANSACTIONS: 'No transactions yet',
  NO_TRANSACTIONS_DESC: 'Add your first transaction to see your spending overview.',
  NO_INSIGHTS: 'No insights available yet',
  NO_INSIGHTS_DESC: 'Keep tracking your spending to get personalized insights.',

  // ─── Errors ─────────────────────────────────────────────
  ERROR_LOADING_DASHBOARD: 'Failed to load dashboard data',
  ERROR_GENERIC: 'Something went wrong',
  RETRY: 'Retry',

  // ─── Auth ───────────────────────────────────────────────
  LOGIN_TITLE: 'Welcome Back',
  LOGIN_SUBTITLE: 'Sign in to manage your finances',
  REGISTER_TITLE: 'Create Account',
  REGISTER_SUBTITLE: 'Start tracking your spending today',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: '••••••••',
  FULL_NAME_LABEL: 'Full Name',
  FULL_NAME_PLACEHOLDER: 'John Doe',
  LOGIN_BUTTON: 'Sign In',
  REGISTER_BUTTON: 'Create Account',
  LOGIN_LINK: 'Already have an account? Sign in',
  REGISTER_LINK: "Don't have an account? Sign up",
  LOGOUT_BUTTON: 'Sign Out',
  AUTH_ERROR_INVALID_CREDENTIALS: 'Invalid email or password',
  AUTH_ERROR_EMAIL_TAKEN: 'An account with this email already exists',
  AUTH_ERROR_WEAK_PASSWORD: 'Password must be at least 8 characters',
  AUTH_ERROR_INVALID_EMAIL: 'Please enter a valid email address',
  AUTH_ERROR_NAME_REQUIRED: 'Full name is required',
  AUTH_ERROR_PHONE_REQUIRED: 'Phone number is required',
  AUTH_ERROR_PHONE_INVALID: 'Please enter a valid phone number',
  FORGOT_PASSWORD_LINK: 'Forgot password?',
  FORGOT_PASSWORD_TITLE: 'Reset Password',
  FORGOT_PASSWORD_SUBTITLE: 'Enter your email and we\'ll send you a reset link',
  FORGOT_PASSWORD_BUTTON: 'Send Reset Link',
  FORGOT_PASSWORD_SUCCESS: 'Check your email for a reset link',
  FORGOT_PASSWORD_BACK: 'Back to Sign In',
  OR_CONTINUE_WITH: 'Or continue with',
  SIGN_IN_WITH_GOOGLE: 'Continue with Google',
  SIGN_IN_WITH_APPLE: 'Continue with Apple',

  // ─── Onboarding ────────────────────────────────────────
  ONBOARDING_TITLE: 'Set Up SANAD',
  ONBOARDING_SUBTITLE: 'Choose your country and currency to get started',
  ONBOARDING_CONTINUE: 'Continue',
  ONBOARDING_CURRENCY_LABEL: 'Currency',
  ONBOARDING_COUNTRY_LABEL: 'Country',
  ONBOARDING_LOADING: 'Setting up…',
  ONBOARDING_LOADING_TITLE: 'Setting up SANAD',
  ONBOARDING_LOADING_SUBTITLE: 'This will just take a moment',

  // ─── Profile / Feature Cards ────────────────────────────
  PROFILE_GOALS: 'Goals',
  PROFILE_SUBSCRIPTIONS: 'Subs',
  PROFILE_BILL_SPLIT: 'Split',
  GOALS_ON_TRACK: 'on track',
  GOALS_AT_RISK: 'at risk',
  GOALS_TRACK_BUDGETS: 'Track budgets',
  SUBS_ACTIVE: 'active',
  SUBS_TRACK_RECURRING: 'Track recurring',
  SPLIT_GROUP: 'group',
  SPLIT_GROUPS: 'groups',
  SPLIT_WITH_FRIENDS: 'Split with friends',

  // ─── Settings / Preferences ─────────────────────────────
  SETTINGS_PREFERENCES: 'Preferences',
  SETTINGS_CURRENCY: 'Currency',
  SETTINGS_APPEARANCE: 'Appearance',
  SETTINGS_LANGUAGE: 'Language',
  SETTINGS_ACCOUNTS: 'Accounts',
  SETTINGS_TOTAL_BALANCE: 'Total Balance',
  SETTINGS_ADD_ACCOUNT: 'Add Account',
  SETTINGS_WHATSAPP: 'WhatsApp',
  SETTINGS_SMS_AUTOMATION: 'SMS Automation',
  SETTINGS_TRASH: 'Trash',
  SETTINGS_TRASH_DESC: 'Recover recently deleted items (7 days)',
  SETTINGS_CATEGORIZE_BY_MERCHANT: 'Categorize by merchant',
  SETTINGS_CATEGORIZE_BY_MERCHANT_DESC: 'Learn from your first category choice for each merchant',
  SETTINGS_STATUS_ON: 'ON',
  SETTINGS_STATUS_OFF: 'OFF',

  // ─── Tabs ───────────────────────────────────────────────
  TAB_HOME: 'Home',
  TAB_TRANSACTIONS: 'Transactions',
  TAB_ANALYTICS: 'Analytics',
  TAB_COINS: 'Assets',
  TAB_PROFILE: 'You',
  TAB_FEATURES: 'Features',

  // ─── Features Tab ───────────────────────────────────────
  FEATURES_HEADER: 'Features',
  FEATURES_SUBHEADER: 'Your tools & insights',
  FEATURES_SUBS_NEXT_UP: 'Next up',
  FEATURES_SUBS_NO_ACTIVE: 'No active subscriptions',
  FEATURES_GOALS_ON_TRACK: 'on track',
  FEATURES_GOALS_EXCEEDED: 'exceeded',
  FEATURES_GOALS_NO_GOALS: 'No budget goals',
  FEATURES_GOALS_AT_RISK: 'at risk',
  FEATURES_SPLIT_COMMUNITIES: 'communities',
  FEATURES_SPLIT_NO_GROUPS: 'No groups yet',
  FEATURES_SPLIT_MEMBERS: 'members',
  FEATURES_CHARITY_TITLE: 'Charity & Giving',
  FEATURES_CHARITY_THIS_MONTH: 'this month',
  FEATURES_CHARITY_THIS_YEAR: 'this year',
  FEATURES_CHARITY_DONATIONS: 'donations',
  FEATURES_CHARITY_NO_GIVING: 'No giving recorded this month',
  FEATURES_CHARITY_TARGET: 'Monthly target',
  FEATURES_CHARITY_NO_TARGET: 'Set a monthly giving target',
  FEATURES_CHARITY_REMAINING: 'remaining',
  FEATURES_CHARITY_OVER_BY: 'over by',
  FEATURES_CHARITY_TOP: 'Top category',
  CHARITY_SCREEN_TITLE: 'Charity & Giving',
  CHARITY_DAILY_TREND: 'Daily giving',
  CHARITY_RECENT: 'Recent donations',
  CHARITY_EMPTY_HEADLINE: 'No donations yet',
  CHARITY_EMPTY_DESC: 'Tap the button below to log your first charity transaction.',
  CHARITY_ADD_DONATION: 'Add donation',
  CHARITY_SET_TARGET_CTA: 'Set monthly target',
  CHARITY_TARGET_HINT: 'Create a budget on a charity category in Goals to set a target.',
  GOALS_TOTAL: 'total goals',
  NEAR_LIMIT: 'near limit',
  ALL_ON_TRACK: 'All on track',
  TXN_CLOSE: 'Close',

  // ─── Smart Input ────────────────────────────────────────
  SMART_INPUT_TITLE: 'Smart Input',
  SMART_INPUT_PLACEHOLDER: 'Describe your transaction...',
  SMART_INPUT_PASTE: 'Paste',
  SMART_INPUT_PASTE_DESC: 'SMS / Text',
  SMART_INPUT_VOICE: 'Voice',
  SMART_INPUT_VOICE_DESC: 'Microphone',
  SMART_INPUT_SCAN: 'Scan',
  SMART_INPUT_SCAN_DESC: 'Receipt OCR',
  SMART_INPUT_PARSE: 'Parse',
  SMART_INPUT_STOP: 'Stop',
  SMART_INPUT_RESET: 'Reset',
  SMART_INPUT_PLACEHOLDER_FULL: 'Describe your transaction...\n"Paid 150 EGP at Carrefour"\n"Salary 8000 EGP received"',
  SMART_INPUT_TRANSCRIBING: 'Transcribing voice…',
  SMART_INPUT_TRANSCRIBING_DESC: 'Processing your audio with AI',
  SMART_INPUT_SCANNING_DESC: 'Extracting details from image',
  SMART_INPUT_PARSING: 'Analyzing your input…',
  SMART_INPUT_PARSING_DESC: 'AI is reading your transaction',
  SMART_INPUT_SUCCESS_ONE: 'Transaction added successfully',
  SMART_INPUT_SUCCESS_MANY: 'transactions added successfully',
  SMART_INPUT_RECORDS_UPDATED: 'Your records have been updated.',
  SMART_INPUT_ADD_ANOTHER: 'Add another transaction',
  SMART_INPUT_VIEW_TRANSACTIONS: 'View transactions',
  SMART_INPUT_BACK_DASHBOARD: 'Back to dashboard',

  // ─── Transaction Filters ────────────────────────────────
  FILTER_ALL: 'All',
  FILTER_EXPENSES: 'Expenses',
  FILTER_INCOME: 'Income',
  FILTER_TRANSFERS: 'Transfers',

  // ─── FeatureGate ────────────────────────────────────────
  FEATURE_AVAILABLE_IN: 'Available in',
  FEATURE_UPGRADE_UNLOCK: 'Upgrade to unlock this feature',
  FEATURE_UPGRADE_TO: 'Upgrade to',

  // ─── Analytics ──────────────────────────────────────────
  ANALYTICS_TITLE: 'Analytics',
  ANALYTICS_SUBTITLE: 'Deeper insights into your spending',
  SPENDING_ANALYSIS: 'Spending Analysis',
  SPENDING_ANALYSIS_DESC: 'How your money breaks down this month',
  STAT_TXN_COUNT: 'Transactions',
  STAT_HABITS_RECURRING: 'Recurring',
  STAT_AVG_PER_DAY: 'Avg / day',
  REGION_BENCHMARK_TITLE: 'Versus people like you',
  REGION_BENCHMARK_DESC: 'Compared to your age group in your region',
  REGION_BENCHMARK_HIGHER: 'higher than peers',
  REGION_BENCHMARK_LOWER: 'lower than peers',
  REGION_BENCHMARK_NO_DATA: 'Not enough data yet for your region.',
  SUBSCRIPTION_SAVINGS_TITLE: 'Plan Savings',
  SUBSCRIPTION_SAVINGS_DESC: 'Switch and save based on your usage pattern',
  SUBSCRIPTION_SAVINGS_SWITCH_TO: 'Switch to',
  SUBSCRIPTION_SAVINGS_SAVE: 'save',
  SUBSCRIPTION_SAVINGS_PER_YEAR: '/yr',
  SUBSCRIPTION_SAVINGS_NO_INSIGHTS: 'No savings opportunities yet. We\u2019ll keep checking.',
  PLAN_TYPE_INDIVIDUAL: 'Individual',
  PLAN_TYPE_FAMILY: 'Family',
  PLAN_TYPE_STUDENT: 'Student',
  PLAN_TYPE_BUNDLE: 'Bundle',
  MONEY_ANALYSIS: 'Money Analysis',
  SAVING_TIPS: 'Saving Tips',
  SUBSCRIPTIONS: 'Subscriptions',
  TRANSACTIONS_LABEL: 'Transactions',
  HABITS_LABEL: 'Habits',
  TOP_CATEGORY: 'Top category',
  BUDGETS: 'Budgets',
  ON_TRACK: 'on track',
  AT_RISK: 'at risk',
  SAVED: 'Saved',
  DEFICIT: 'Deficit',
  BUDGET_STATUS: 'Budget Status',
  EXPENSE_TREND: 'Expense Trend',
  TREND_DAILY: 'Daily',
  TREND_WEEKLY: 'Weekly',
  TREND_MONTHLY: 'Monthly',
  NO_EXPENSES_YET: 'No expenses yet',
  SPENDING_HABITS: 'Spending Habits',
  SPENDING_PATTERNS: 'Your Spending Patterns',
  SPENDING_PATTERNS_DESC: 'These patterns appear often in your spending and are worth keeping an eye on.',
  ADD_TXN_ANALYSIS: 'Add transactions to see your spending analysis.',
  NO_DATA_MONTH: 'No data for this month yet.',
  // Saving Tips
  PEERS_SPEND_LESS: 'People your age in your area spend less on',
  PEERS_THAN_YOU: 'than you do.',
  IF_REDUCED_5: 'If reduced by 5%, save',
  PER_MONTH: '/month',
  BIGGEST_SPEND: 'Your biggest spend is',
  SMALL_CUT: '. A small cut here goes a long way.',
  ADD_TXN_TIPS: 'Add transactions to unlock personalized saving tips.',
  NOT_ENOUGH_DATA: 'Not enough data for your age group and area yet.\nCheck back next month.',
  SAVING_OPPORTUNITY: 'SAVING OPPORTUNITY',
  CUT_OVERSPENDING: 'If you reduce overspending in',
  CUT_OVERSPENDING_SUFFIX: 'by 5%, you could save',
  PER_YEAR_LABEL: '/year',
  WHERE_SAVE: 'Where You Can Save',
  WHERE_CUT: 'Where You Can Cut Back',
  FIVE_PCT_CUT: '5% cut →',
  COMPARED_MORE: 'Compared to people your age in your area, you spend',
  MORE_ON_THIS: 'on this.',
  MORE_PERCENT: '% more',
  LESS_PERCENT: '% less',
  HOW_COMPARE: 'How You Compare',
  HOW_COMPARE_DESC: 'Compared to people your age and in your region:',
  GREAT_JOB: 'Great job!',
  SPENDING_BELOW: "You're spending at or below what people your age in your area typically spend.",
  YOU: 'You',
  TYPICAL: 'Typical',
  // Subscriptions
  ACTIVE: 'active',
  DUE_THIS_MONTH_SUBS: 'due this month',
  NO_SUBS_YET: 'No subscriptions tracked yet',
  NO_SUBS_ADDED: 'No subscriptions added yet.\nGo to the Subscriptions tab to add them.',
  PER_YEAR: 'Per Year',
  BILLING_SPLIT: 'Billing Split',
  MONTHLY_LABEL: 'Monthly',
  QUARTERLY_LABEL: 'Quarterly',
  YEARLY_LABEL: 'Yearly',
  UPCOMING_BILLING: 'Upcoming Billing',
  IN_DAYS: 'In',
  PAUSED: 'Paused',

  // ─── Assets ─────────────────────────────────────────────
  TOTAL_ASSET_VALUE: 'Total Asset Value',
  GOLD: 'Gold',
  SILVER: 'Silver',
  CRYPTO: 'Crypto',
  STOCKS: 'Stocks',
  TRACK_ASSETS: 'Track Your Assets',
  TRACK_ASSETS_DESC: 'Add gold, silver, or crypto holdings',
  ADD: 'Add',
  ASSETS_TITLE: 'Assets',
  ASSETS_PHYSICAL: 'Physical Assets',
  ASSETS_STOCKS: 'Stocks',
  STOCKS_SUBTITLE: 'Popular · Add your favorites',
  ASSETS_COMMODITIES_CRYPTO: 'Commodities & Crypto',
  ASSETS_LIVE_PRICES: 'Live market prices',
  ASSETS_BREAKDOWN: 'Asset Breakdown',
  NO_DATA: 'No data',
  ADD_ASSET: 'Add Asset',
  ASSET_TYPE: 'Asset Type',
  UNIT: 'Unit',
  QUANTITY: 'Quantity',
  AVG_BUY_PRICE: 'Average Buy Price',
  OPTIONAL_PER: 'optional, per',
  SAVE_CHANGES: 'Save Changes',
  DELETE_ASSET: 'Delete Asset',
  DELETE_ASSET_CONFIRM: 'Remove from your portfolio?',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  INSIGHTS: 'Insights',
  CURRENT_PRICE: 'Current price',
  CURRENT_VALUE: 'Current Value',
  LEAVE_EMPTY_REMOVE: 'Leave empty to remove',
  FAILED_LOAD_ASSETS: 'Failed to load assets',
  INSIGHT_GOLD_HEAVY: 'Your portfolio is heavily concentrated in gold. Consider diversifying into other asset classes.',
  INSIGHT_CRYPTO_HEAVY: 'Crypto makes up most of your portfolio. This is a volatile asset — consider balancing with stable assets like gold.',
  INSIGHT_STOCK_HEAVY: 'Stocks are most of your allocation right now. Keep an eye on sector concentration risk.',
  INSIGHT_DIVERSIFIED: 'Good diversification! You have exposure across metals, crypto, and stocks.',
  INSIGHT_PORTFOLIO_UP: 'Your portfolio is up',
  INSIGHT_PORTFOLIO_DOWN: 'Your portfolio is down',
  INSIGHT_FROM_BUY: 'from your buy prices.',
  INSIGHT_HOLD_STEADY: 'from your buy prices. Hold steady — markets fluctuate.',
  INSIGHT_ADD_BUY_PRICE: 'Add buy prices to',
  INSIGHT_TRACK_GAINS: 'to track gains/losses.',
  PHYSICAL_ASSETS: 'Physical Assets',
  YOUR_HOLDINGS: 'Your holdings',
  PORTFOLIO: 'Portfolio',
  LAST_30_DAYS: 'Last 30 days',
  ADD_HOLDING_PROMPT: 'What would you like to add?',
  ADD_HOLDING_ASSET_DESC: 'Gold, silver, BTC, ETH',
  ADD_HOLDING_STOCK_DESC: 'Track shares you own',
  TIME_DAY: '1D',
  TIME_WEEK: '1W',
  TIME_MONTH: '1M',
  TIME_3M: '3M',
  TIME_YEAR: '1Y',
  TIME_ALL: 'All',
  SHARES_UNIT: 'share',
  AI_ASSETS_FORECAST: 'AI asset forecasts',
  AI_ASSETS_FORECAST_DESC: 'Available on Max · Upgrade to unlock',
  UPGRADE_CTA: 'Upgrade',
  ASSETS_SUBTITLE: 'Your investment portfolio',
  WINNING_ASSET_THIS_MONTH: 'Top performer this month',
  LIVE_METAL_CRYPTO_PRICES: 'Gold & Crypto prices',
  LIVE_STOCK_PRICES: 'Stock prices',
  LAST_UPDATED: 'Last updated',
  SMART_INSIGHTS: 'Smart insights',
  INSIGHT_CONCENTRATION_SENTENCE: '{pct}% of your portfolio is concentrated in {name}.',
  INSIGHT_CONCENTRATION_WARN: 'Consider diversifying into other asset classes.',
  INSIGHT_OVERALL_UP_SENTENCE: "You're up {pct}% on your buy prices overall.",
  INSIGHT_OVERALL_DOWN_SENTENCE: "You're down {pct}% on your buy prices overall.",
  INSIGHT_BEST_GAINER_SENTENCE: '{name} is your best performer, up {pct}%.',
  INSIGHT_NO_BUY_PRICES: 'Add buy prices to your assets to see overall returns.',
  DIST_STOCKS: 'Stocks',
  DIST_GOLD: 'Gold',
  DIST_CRYPTO: 'Crypto',
  DIST_SILVER: 'Silver',
  DIST_OTHER: 'Other',
  PORTFOLIO_ALLOCATION_TITLE: 'Portfolio Allocation',
  PORTFOLIO_TOTAL_LABEL: 'Total',
  SHOW_ALL: 'Show all',
  SHOW_LESS: 'Show less',
  CURRENCY_TOGGLE_LOCAL: 'Local',
  CURRENCY_TOGGLE_USD: 'USD',
  ENTER_PRICE_IN: 'Enter price in',
  DEV_TOOLS_SECTION: 'Developer tools',
  DEV_PLAN_LABEL: 'Simulated plan',
  DEV_PLAN_HINT: 'Override the active plan for testing',
  PER_MONTH_SHORT: '/mo',
  PER_QUARTER_SHORT: '/3mo',
  PER_YEAR_SHORT: '/yr',
  ALL_FILTER: 'All',

  // ─── Add Transaction ────────────────────────────────────
  ADD_TRANSACTION: 'Add Transaction',
  AMOUNT: 'Amount',
  TYPE: 'Type',
  NOTES: 'Notes',
  MERCHANT: 'Merchant',
  DESCRIPTION: 'Description',
  DESCRIPTION_PLACEHOLDER: 'e.g. Grocery shopping',
  CATEGORY: 'Category',
  ACCOUNT: 'Account',
  ACCOUNT_OPTIONAL: '(optional)',
  DATE: 'Date',
  NOTES_OPTIONAL: 'Notes (optional)',
  NOTE_PLACEHOLDER: 'Add a note…',
  SAVING: 'Saving…',
  ADD_EXPENSE: 'Add Expense',
  ADD_INCOME: 'Add Income',
  ERROR_VALID_AMOUNT: 'Enter a valid amount',
  ERROR_SELECT_CATEGORY: 'Select a category',
  ERROR_ENTER_DESCRIPTION: 'Enter a description',

  // ─── Dashboard Labels ───────────────────────────────────
  WELCOME_BACK: 'Welcome Back',
  CURRENT_BALANCE: 'Current Balance',
  SPENDING: 'Spending',
  TOTAL_ASSETS: 'Total Assets',
  CASH: 'Cash',
  BANK: 'Bank',
  SAVINGS: 'Savings',
  CREDIT: 'Credit',
  UPCOMING_PAYMENTS: 'Upcoming Payments',
  NO_UPCOMING_SUBS: 'No upcoming subscription payments',
  NO_TRANSACTIONS_MONTH: 'No transactions this month',
  DUE_THIS_MONTH: 'due this month',
  RECURRENCE_YEARLY: 'Yearly',
  RECURRENCE_QUARTERLY: 'Quarterly',
  RECURRENCE_MONTHLY: 'Monthly',
  RECURRENCE_CUSTOM: 'Custom',
  DUE: 'Due',
  OVERDUE: 'Overdue',
  TODAY: 'Today',
  TOMORROW: 'Tomorrow',
  UNCATEGORIZED: 'Uncategorized',

  // ─── Community ──────────────────────────────────────────
  COMMUNITY: 'Community',
  COMMUNITY_SUBTITLE: 'Split bills with your group',
  NEW_COMMUNITY: 'New Community',
  COMMUNITY_NAME: 'Community Name',
  COMMUNITY_NAME_PLACEHOLDER: 'e.g. Dinner Group, Trip to Hurghada…',
  CREATE_COMMUNITY: 'Create Community',
  NO_COMMUNITIES: 'No Communities',
  NO_COMMUNITIES_DESC: 'Create a group to split bills with\nfriends, family or colleagues.',
  MEMBER: 'member',
  MEMBERS: 'members',
  ADMIN: 'Admin',
  MEMBER_ROLE: 'Member',
  ERROR_TITLE: 'Error',
  ERROR_CREATE_COMMUNITY: 'Could not create community. Please try again.',
  COULD_NOT_LOAD_COMMUNITIES: 'Could not load communities',
  ADD_MEMBER: 'Add Member',
  ADD_MEMBER_SEARCH: 'Search by name or email...',
  SPLIT_EVENTS: 'Split Events',
  NO_SPLIT_EVENTS: 'No split events yet',
  NO_SPLIT_EVENTS_DESC: 'Tap + to create one and attach a receipt.',
  ADDED_BADGE: 'Added',
  NO_USERS_FOUND: 'No users found for',
  CREATE_AND_SPLIT: 'Create & Split',

  // ─── SMS Review ─────────────────────────────────────────
  SMS_REVIEW_HEADER: 'Review',
  SMS_ORIGINAL: 'ORIGINAL SMS',
  SMS_BACK: 'Back',
  SMS_SKIP: 'Skip',
  SMS_SAVE_NEXT: 'Save & Next',
  SMS_SAVE_DONE: 'Save & Done',
  SMS_SUGGESTED_TEMPLATE: '(suggested: {name})',

  // ─── AI Insight Card ────────────────────────────────────
  AI_INSIGHT_VIEW_DETAILS: 'View Details',
  AI_INSIGHT_TAP_HINT: 'Tap to expand · Long press to dismiss',
  AI_INSIGHT_TYPE_ALERT: '⚠ Alert',
  AI_INSIGHT_TYPE_SAVING: '💡 Saving Tip',
  AI_INSIGHT_TYPE_TREND: '📈 Trend',
  AI_INSIGHT_TYPE_SPENDING: '💸 Spending',
  AI_INSIGHT_TYPE_BUDGET: '📊 Budget',

  // ─── Benchmark Unlock ───────────────────────────────────
  BENCHMARK_UNLOCK_TITLE: 'See How You Compare',
  BENCHMARK_UNLOCK_DESC: 'Add your age and region to see how your spending compares to anonymous SANAD users like you.',

  // ─── Create Group CTA ───────────────────────────────────
  CREATE_GROUP_ADD_TX_CTA: 'Add a Transaction',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_DELETE_PERMANENTLY: 'Delete Permanently',
  TRASH_DELETE_CONFIRM_SUFFIX: 'will be gone forever. Continue?',
  ASSET_RESET_FAILED: 'Reset failed',
  UNKNOWN_ERROR: 'Unknown error',

  // ─── Edit Transaction ───────────────────────────────────
  EDIT_TRANSACTION: 'Edit Transaction',
  EXCLUDE_INSIGHTS: 'Exclude from insights',
  UNCATEGORIZED_COUNT_SUFFIX: 'uncategorized',
  TAP_TO_REVIEW: 'Tap to review and categorize',
  CHOOSE_GROUP_SPLIT: 'Choose Group to Split',
  SPLITTING: 'Splitting',
  NEW_GROUP_NAME: 'New Group Name',
  NEW_GROUP_PLACEHOLDER: 'e.g. Dinner Group',

  // ─── SMS Review ─────────────────────────────────────────
  TRANSACTION_TO_REVIEW: 'transaction to review',
  TRANSACTIONS_TO_REVIEW: 'transactions to review',
  MORE: 'more',

  // ─── Account Picker ─────────────────────────────────────
  NO_ACCOUNTS_YET: 'No accounts yet. Add one in Settings.',

  // ─── Common ─────────────────────────────────────────────
  SAVE: 'Save',
  DONE: 'Done',
  LOADING: 'Loading...',
  EXPENSE: 'Expense',
  INCOME: 'Income',
  TRANSFER: 'Transfer',

  // ─── Appearance ─────────────────────────────────────────
  APPEARANCE_LIGHT: 'Light',
  APPEARANCE_DARK: 'Dark',
  APPEARANCE_SYSTEM: 'System',

  // ─── Date Range Presets ─────────────────────────────────
  DATE_TODAY: 'Today',
  DATE_THIS_WEEK: 'This Week',
  DATE_THIS_MONTH: 'This Month',
  DATE_LAST_MONTH: 'Last Month',
  DATE_LAST_3_MONTHS: 'Last 3 Mo',
  DATE_YEAR_TO_DATE: 'YTD',
  DATE_CUSTOM: 'Custom',
  DATE_SELECT_RANGE: 'Select Date Range',
  DATE_FROM: 'From',
  DATE_TO: 'To',
  DATE_SELECT: 'Select',

  // ─── Day Labels (MENA week starts Saturday) ─────────────
  DAY_SA: 'Sa',
  DAY_SU: 'Su',
  DAY_MO: 'Mo',
  DAY_TU: 'Tu',
  DAY_WE: 'We',
  DAY_TH: 'Th',
  DAY_FR: 'Fr',

  // ─── Day Names ──────────────────────────────────────────
  DAY_SUN: 'Sun',
  DAY_MON: 'Mon',
  DAY_TUE: 'Tue',
  DAY_WED: 'Wed',
  DAY_THU: 'Thu',
  DAY_FRI: 'Fri',
  DAY_SAT: 'Sat',

  // ─── Horizon Periods ────────────────────────────────────
  HORIZON_1_MO: '1 mo',
  HORIZON_2_MO: '2 mo',
  HORIZON_3_MO: '3 mo',
  HORIZON_6_MO: '6 mo',

  // ─── Frequency Labels ───────────────────────────────────
  FREQ_DAILY: 'Daily',
  FREQ_WEEKLY: 'Weekly',
  FREQ_BIWEEKLY: 'Bi-weekly',
  FREQ_MONTHLY: 'Monthly',
  FREQ_RECURRING: 'Recurring',

  // ─── Habit Section ──────────────────────────────────────
  HABITS_DETECTED: 'Habits detected',
  HABIT_SPEND: 'Habit spend',
  OF_SPENDING: 'Of spending',
  SHOW_ALL_HABITS: 'Show all',

  // ─── Subscription Details ───────────────────────────────
  SUBS_DELETE_TITLE: 'Delete',
  SUBS_DELETE_CONFIRM: 'Remove this subscription?',
  SUBS_MARK_PAID_TITLE: 'Mark as Paid',
  SUBS_MARK_PAID_CONFIRM: 'This will advance the next billing date. Continue?',
  SUBS_PAID: 'Paid',
  SUBS_PAUSE: 'Pause',
  SUBS_RESUME: 'Resume',
  SUBS_MONTHLY_TOTAL: 'Monthly Total',
  SUBS_TOTAL_NEXT_1_MO: 'Next month total',
  SUBS_TOTAL_NEXT_N_MO: 'Next {n} months total',
  // Voice recording overlay + processing sheet
  VOICE_RECORDING_TITLE: 'Listening…',
  VOICE_RECORDING_SUB: 'Speak naturally — tap stop when you\'re done.',
  PROCESSING_AUDIO_TITLE: 'Converting your voice to text',
  PROCESSING_AUDIO_SUB: 'We\'re listening to your recording and writing what we hear.',
  PROCESSING_STAGE_LOAD: 'Loading file',
  PROCESSING_STAGE_CLEAN: 'Cleaning audio',
  PROCESSING_STAGE_TRANSCRIBE: 'Converting to text',
  PROCESSING_STAGE_FORMAT: 'Formatting result',
  MINIMIZE: 'Minimize',
  MINI_PROCESSING_LABEL: 'Processing voice note…',
  PICK_MONTH: 'Pick month',
  NO_BUDGETS: 'No budgets yet',
  HORIZON_CUSTOM: 'Custom',
  PICK_HORIZON_MONTH: 'Show until',
  SUBS_TOTAL_UNTIL: 'Total until selected month',
  SUBS_TOTAL_UNTIL_THIS_MONTH: 'Total until this month',
  SUBS_ADD: 'Add Subscription',
  SUBS_TRACK_RECURRING_PAYMENTS: 'Track your recurring payments',
  SUBS_BILLING_MONTHLY: 'Monthly',
  SUBS_BILLING_MONTHLY_SHORT: '/mo',
  SUBS_BILLING_QUARTERLY: 'Quarterly',
  SUBS_BILLING_QUARTERLY_SHORT: '/3mo',
  SUBS_BILLING_YEARLY: 'Yearly',
  SUBS_BILLING_YEARLY_SHORT: '/yr',

  // ─── Commitment / Due ───────────────────────────────────
  DUE_OVERDUE_DAYS: 'd overdue',
  DUE_TODAY_LABEL: 'Due today',
  DUE_TOMORROW_LABEL: 'Due tomorrow',
  DUE_DAYS_LEFT: 'd left',

  // ─── Goals ──────────────────────────────────────────────
  GOALS_TITLE: 'Budget Goals',
  GOALS_PERIOD: 'Period',
  GOALS_PERIOD_WEEKLY: 'Weekly',
  GOALS_PERIOD_MONTHLY: 'Monthly',
  GOALS_PERIOD_YEARLY: 'Yearly',

  // ─── WhatsApp / SMS Alerts ──────────────────────────────
  ALERT_INVALID_NUMBER: 'Invalid number',
  ALERT_INVALID_NUMBER_MSG: 'Enter your full WhatsApp number with country code (e.g. +966512345678)',
  ALERT_WHATSAPP_NOT_FOUND: 'WhatsApp not found',
  ALERT_WHATSAPP_NOT_FOUND_MSG: 'Please install WhatsApp to use this feature.',
  ALERT_TEST_FAILED: 'Test Failed',
  ALERT_TEST_FAILED_MSG: 'Could not open the deep link. Make sure the app is installed.',
  ALERT_IOS_ONLY: 'iOS Only',
  ALERT_IOS_ONLY_MSG: 'Shortcuts automation is available on iPhone only. On Android, SMS is read automatically when permission is granted.',

  // ─── Smart Input Alerts ─────────────────────────────────
  ALERT_LIMIT_REACHED: 'Limit Reached',
  ALERT_PERMISSION_REQUIRED: 'Permission Required',
  ALERT_PERMISSION_MIC: 'Microphone permission is needed for voice input.',
  ALERT_PERMISSION_CAMERA: 'Camera permission is needed for receipt scanning.',
  ALERT_PERMISSION_GALLERY: 'Gallery permission is needed for receipt scanning.',
  ALERT_FAILED_RECORDING: 'Failed to start recording. Please check microphone permissions.',
  ALERT_FAILED_CAPTURE: 'Failed to capture image',
  ALERT_FAILED_SELECT: 'Failed to select images',
  SMART_INPUT_AMOUNT_PLACEHOLDER: '0.00',
  SMART_INPUT_DESC_PLACEHOLDER: 'Transaction description',
  SMART_INPUT_MERCHANT_PLACEHOLDER: 'Merchant name',
  SMART_INPUT_PERSON_PLACEHOLDER: 'Person name',
  SMART_INPUT_DATE_PLACEHOLDER: 'YYYY-MM-DD',
  SMART_INPUT_NOTE_PLACEHOLDER: 'Add a note…',
  SMART_INPUT_CAMERA: 'Camera',
  SMART_INPUT_GALLERY: 'Gallery',

  // ─── Review Screen ──────────────────────────────────────
  REVIEW_DONE_VOICE: 'transaction(s) from voice.',
  REVIEW_DONE_RECEIPTS: 'transaction(s) from receipts.',
  REVIEW_NO_RESULTS: 'No Results',
  REVIEW_NO_RESULTS_MSG: 'Could not extract amounts from the receipt(s).',
  REVIEW_VOICE_FAILED: 'Voice transcription failed',
  REVIEW_RECEIPT_FAILED: 'Receipt scanning failed',
  REVIEW_SCAN_RECEIPT: 'Scan Receipt',
  REVIEW_CHOOSE_SOURCE: 'Choose a source',
  REVIEW_ALL_CAUGHT_UP: 'All caught up!',
  REVIEW_CAMERA_NEEDED: 'Camera permission needed.',
  REVIEW_GALLERY_NEEDED: 'Gallery permission needed.',

  // ─── Split Event Alerts ─────────────────────────────────
  SPLIT_OCR_FAILED: 'OCR Failed',
  SPLIT_OCR_FAILED_MSG: 'Could not read the receipt. You can fill in items manually.',
  SPLIT_MISSING_TITLE: 'Missing Title',
  SPLIT_MISSING_TITLE_MSG: 'Please enter a name for this event.',
  SPLIT_NO_ITEMS: 'No Items',
  SPLIT_NO_ITEMS_MSG: 'Please add at least one item with a price.',
  SPLIT_ADD_PEOPLE: 'Add People',
  SPLIT_ADD_PEOPLE_MSG: 'Add at least one person to split with.',
  SPLIT_CREATE_FAILED: 'Could not create split event. Please try again.',
  SPLIT_CAMERA_NEEDED: 'Camera access is needed to scan receipts.',
  SPLIT_SAVE_FAILED: 'Could not save assignments.',
  SPLIT_SETTLE_FAILED: 'Could not compute settlements. Make sure all items are assigned.',
  SPLIT_NEW: 'New Split',
  SPLIT_TOTAL: 'Total',
  SPLIT_CREATE: 'Create',
  SPLIT_EVENT_NAME: 'EVENT NAME',
  SPLIT_EVENT_PLACEHOLDER: 'e.g. Dinner at Koshary El Tahrir',
  SPLIT_WITH: 'SPLIT WITH',
  SPLIT_SEARCH_PEOPLE: 'Search by name or email…',
  SPLIT_SCAN_RECEIPT: 'Scan Receipt',
  SPLIT_FROM_GALLERY: 'From Gallery',
  SPLIT_ADD_ITEM: 'Add Item',
  SPLIT_QTY: 'Qty',
  SPLIT_PRICE: 'Price',
  SPLIT_EXTRAS: 'EXTRAS',

  // ─── Smart Input Card Labels ──────────────────────────────
  SMART_INPUT_SAVED: 'Saved',
  SMART_INPUT_TRANSACTION_N: 'Transaction',
  SMART_INPUT_LOW_CONFIDENCE: 'Low confidence. Please verify the details.',
  SMART_INPUT_MORE_DETAILS: 'More details',
  SMART_INPUT_LESS_DETAILS: 'Less details',
  SMART_INPUT_SELECT_CATEGORY: 'Select a category to save',
  SMART_INPUT_SAVE_ALL: 'Save All',
  SMART_INPUT_SCAN_COMPLETE: 'Scan Complete',
  SMART_INPUT_SCAN_PROGRESS: 'Scanning receipt',
  SMART_INPUT_SCAN_OF: 'of',
  SMART_INPUT_SCANNED_OK: 'scanned successfully',
  SMART_INPUT_SCANNED_FAILED: 'failed',
  SMART_INPUT_INPUT_LABEL: 'Input',
  SMART_INPUT_TXN_DETECTED: 'transactions detected',
  SMART_INPUT_X_SAVED: 'saved',
  SMART_INPUT_CONFIDENCE_HIGH: 'High',
  SMART_INPUT_CONFIDENCE_MEDIUM: 'Medium',
  SMART_INPUT_CONFIDENCE_LOW: 'Low',

  // ─── Review Screen Labels ──────────────────────────────────
  REVIEW_TITLE: 'Review',
  REVIEW_NEEDS_ATTENTION: 'need your attention',
  REVIEW_TRANSACTION_TYPE: 'Transaction Type',
  REVIEW_CATEGORY_OPTIONAL: 'Category',
  REVIEW_CONFIRM: 'Confirm',
  REVIEW_SAVE_UNCATEGORIZED: 'Save Uncategorized',
  REVIEW_DISCARD_TITLE: 'Discard Transaction',
  REVIEW_DISCARD_MSG_PREFIX: 'Delete "',
  REVIEW_DISCARD_MSG_SUFFIX: '"? This cannot be undone.',
  REVIEW_NO_MATCH: 'No Match',
  REVIEW_CATEGORIZED: 'Categorized',
  REVIEW_CREATED: 'Created',
  REVIEW_EXISTING: 'existing',
  REVIEW_NEW: 'new',
  REVIEW_MATCHED: 'Matched',
  REVIEW_TAP_STOP: 'Tap to Stop',
  REVIEW_RECORDING: 'Recording...',
  REVIEW_VOICE: 'Voice',
  REVIEW_VOICE_HINT: 'Say "#1 is groceries"',
  REVIEW_CAMERA_OR_GALLERY: 'Camera or gallery',
  REVIEW_NO_REVIEW_DESC: 'No transactions need review right now.',
  REVIEW_SAVE_ALL: 'Save all',
  REVIEW_SAVE_ALL_READY: 'ready',
  REVIEW_SAVE_ALL_NONE_READY: 'Pick a category to enable',
  REVIEW_SAVE_ALL_PROGRESS: 'Saving',
  REVIEW_SAVE_ALL_DONE: 'Saved',
  REVIEW_SAVE_ALL_FAILED: 'Some rows failed',

  // ─── Split Event Labels ─────────────────────────────────────
  SPLIT_WHO_ORDERED: 'Who ordered:',
  SPLIT_SHARE_HINT: 'Select everyone who shares this item. It will be split equally.',
  SPLIT_SAVE_ASSIGNMENT: 'Save Assignment',
  SPLIT_TAP_ASSIGN: 'Tap to assign',
  SPLIT_COULD_NOT_LOAD: 'Could not load event.',
  SPLIT_SUBTOTAL: 'Subtotal',
  SPLIT_TAX: 'Tax',
  SPLIT_SERVICE_FEE: 'Service Fee / Tip',
  SPLIT_DISCOUNT: 'Discount',
  SPLIT_ITEMS: 'ITEMS',
  SPLIT_UNASSIGNED: 'unassigned',
  SPLIT_ASSIGN_MORE: 'Assign',
  SPLIT_MORE_ITEMS: 'more item(s)',
  SPLIT_CALCULATE: 'Calculate Who Owes What',
  SPLIT_SETTLEMENTS: 'SETTLEMENTS',
  SPLIT_PAID_COUNT: 'paid',
  SPLIT_EACH_PAYS: 'Each person pays',
  SPLIT_ITEMS_LABEL: 'Items:',
  SPLIT_EXTRAS_LABEL: 'Extras:',

  // ─── Trash ──────────────────────────────────────────────
  TRASH_TITLE: 'Trash',

  // ─── Month Names (for localized date display) ───────────
  MONTH_JAN: 'January',
  MONTH_FEB: 'February',
  MONTH_MAR: 'March',
  MONTH_APR: 'April',
  MONTH_MAY: 'May',
  MONTH_JUN: 'June',
  MONTH_JUL: 'July',
  MONTH_AUG: 'August',
  MONTH_SEP: 'September',
  MONTH_OCT: 'October',
  MONTH_NOV: 'November',
  MONTH_DEC: 'December',

  // ─── Add Member ─────────────────────────────────────────
  ALERT_ADD_MEMBER_FAILED: 'Could not add member.',

  // ─── SMS Profile Section ────────────────────────────────
  SMS_RECOMMENDED: 'Recommended: iOS Shortcuts',
  SMS_ALTERNATIVE: 'Alternative: Paste SMS in Smart Input',
  SMS_SETUP_GUIDE: 'Setup guide',
  SMS_SHOW_STEPS: 'Show steps',
  SMS_OPEN_SHORTCUTS: 'Open Shortcuts App',
  SMS_TEST_LINK: 'Test Link',
  SMS_PASTE: 'Paste SMS',
  SMS_AUTO_IMPORT: 'Auto-import bank SMS',

  // ─── Subscriptions Screen ───────────────────────────────
  SUBS_NO_YET: 'No subscriptions yet',
  SUBS_NO_YET_DESC: 'Add your recurring payments to track them.',

  // ─── Profile – WhatsApp ─────────────────────────────────
  WHATSAPP_TITLE: 'WhatsApp Integration',
  WHATSAPP_CONNECTED: 'Connected — send expenses via WhatsApp',
  WHATSAPP_NOT_CONNECTED: 'Log expenses by texting on WhatsApp',
  WHATSAPP_NUMBER_LABEL: 'Your WhatsApp number',
  WHATSAPP_DISCONNECT: 'Disconnect',
  WHATSAPP_SAVED: 'Saved ✓',
  WHATSAPP_CONNECT: 'Connect',
  WHATSAPP_SANDBOX_TITLE: 'Step 2: Join the Sandbox',
  WHATSAPP_SANDBOX_DESC: 'Send the join keyword to our WhatsApp number so messages get routed to your account.',
  WHATSAPP_OPEN_JOIN: 'Open WhatsApp & Join',
  WHATSAPP_USAGE_HINT: 'After joining, text your expenses to the WhatsApp number:\n"Paid 150 EGP at Carrefour"\n"دفعت ٢٠٠ جنيه كارفور"\nYou\'ll get a confirmation reply and see it in SANAD.',

  // ─── Profile – SMS Setup ────────────────────────────────
  SMS_SUBTITLE: 'Capture transactions automatically via iOS Shortcuts',
  SMS_SHORTCUTS_DESC: 'Create an automation that triggers when you receive a bank SMS, and sends it to SANAD automatically.',
  SMS_PASTE_DESC: 'Copy any bank SMS and paste it in Smart Input. SANAD parses amount, merchant, and type.',
  SMS_DEEP_LINK_LABEL: 'Your SMS deep link',
  SMS_COPIED: 'Copied',
  SMS_COPY: 'Copy',
  SMS_SENT: 'Sent!',
  SMS_STEP_1_TITLE: 'Tap a bank preset above',
  SMS_STEP_1_DESC: 'We copy the two things you need (sender filter + Open URL action) and open the Shortcuts app for you.',
  SMS_STEP_2_TITLE: 'Paste into a new Automation',
  SMS_STEP_2_DESC: 'In Shortcuts → Automation → Message, paste the sender, add "Open URL" action and paste the URL. Turn off "Ask Before Running". Done.',
  SMS_STEP_3_TITLE: 'Create Personal Automation',
  SMS_STEP_3_DESC: 'Tap "+", then "Message". Set the sender to your bank (e.g. "CIB", "NBE", "QNB").',
  SMS_STEP_4_TITLE: 'Add "Open URL" action',
  SMS_STEP_4_DESC: 'Search for "Open URL" and add it. Set the URL to:\nsanad://sms?text=\nThen tap "Shortcut Input" or "Message" variable to append the SMS body.',
  SMS_STEP_5_TITLE: 'Disable \'Ask Before Running\'',
  SMS_STEP_5_DESC: 'Toggle off \'Ask Before Running\' so it processes silently in the background.',
  SMS_STEP_6_TITLE: 'Done!',
  SMS_STEP_6_DESC: 'Bank SMS will now auto-create transactions in SANAD. Check the transactions list for review.',
  SMS_PRO_TIP: 'Pro tip',
  SMS_PRO_TIP_DESC: 'In Step 4, after pasting the deep link URL, you need to add the message body as a variable. Tap after the "text=" part, then insert the "Shortcut Input" or "Message" variable from the magic variable list.',
  SMS_FUTURE_NOTE: 'A future update will add a native "Process SMS in SANAD" action that appears directly in the Shortcuts app — no URL copy needed.',

  // ─── SMS Shortcut Presets ─────────────────────────────────
  SMS_PRESETS_TITLE: 'Bank Shortcut Presets',
  SMS_PRESETS_SUBTITLE: 'One-tap setup for your bank',
  SMS_PRESETS_HINT: 'Tap "Set up" — we copy the sender filter and deep link, then open Shortcuts. Paste into the Message automation and you\'re done.',
  SMS_PRESETS_GROUP_SA: 'SAUDI BANKS',
  SMS_PRESETS_GROUP_EG: 'EGYPTIAN BANKS',
  SMS_PRESET_SENDER: 'Sender',
  SMS_PRESET_SETUP: 'Set up',
  SMS_PRESET_READY: 'Copied!',
  SMS_PRESET_TEST: 'Test',
  SMS_PRESET_COPIED_TITLE: 'Setup copied',
  SMS_PRESET_COPIED_MSG: 'Open Shortcuts → Automation → Message. Use "{sender}" as the sender, then paste the Open URL action.',

  // ─── Profile – Currency ─────────────────────────────────
  CURRENCY_SAR: 'Saudi Riyal',
  CURRENCY_AED: 'UAE Dirham',
  CURRENCY_EGP: 'Egyptian Pound',
  CURRENCY_KWD: 'Kuwaiti Dinar',
  CURRENCY_QAR: 'Qatari Riyal',
  CURRENCY_BHD: 'Bahraini Dinar',
  CURRENCY_OMR: 'Omani Rial',
  CURRENCY_JOD: 'Jordanian Dinar',
  CURRENCY_USD: 'US Dollar',
  CURRENCY_EUR: 'Euro',
  CURRENCY_GBP: 'British Pound',

  // ─── Profile – Account Types ────────────────────────────
  ACCOUNT_CASH: 'Cash',
  ACCOUNT_BANK: 'Bank Account',
  ACCOUNT_SAVINGS: 'Savings',
  ACCOUNT_CREDIT_CARD: 'Credit Card',

  // ─── Trash Screen ──────────────────────────────────────
  TRASH_HEADER: 'Trash',
  TRASH_SUBTITLE: 'Items auto-delete after 7 days',
  TRASH_EMPTY_TITLE: 'Trash is empty',
  TRASH_EMPTY_DESC: 'Deleted transactions and assets appear here for 7 days.',

  // ─── Subscriptions Screen Labels ────────────────────────
  SUBS_HEADER: 'Subscriptions',
  SUBS_TRACK_DESC: 'Track your recurring payments',
  SUBS_CHOOSE: 'Choose Subscription',
  SUBS_DETAILS: 'Subscription Details',
  SUBS_FORM_NAME: 'Name',
  SUBS_FORM_AMOUNT: 'Amount',
  SUBS_FORM_CYCLE: 'Billing Cycle',
  SUBS_FORM_NEXT_BILLING: 'Next Billing Date',
  SUBS_FORM_DAY: 'Day',
  SUBS_FORM_MONTH: 'Month',
  SUBS_FORM_YEAR: 'Year',
  SUBS_FORM_CATEGORY: 'Category',
  SUBS_CUSTOM: 'Add Custom Subscription',
  SUBS_ADD_SUB: 'Add Subscription',
  SUBS_BACK_PRESETS: '← Back to presets',
  SUBS_MONTHLY_TOTAL_LABEL: 'Monthly Total',
  SUBS_ACTIVE_PAUSED: 'active',
  SUBS_PAUSED_LABEL: 'paused',
  SUBS_DUE_THIS_MONTH: 'Due This Month',
  SUBS_UPCOMING: 'Upcoming',
  SUBS_NO_UPCOMING: 'No upcoming payments in this period',
  SUBS_PAUSED_SECTION: 'Paused',
  SUBS_PLACEHOLDER_NAME: 'e.g. Netflix, Gym, VPN',
  SUBS_PLACEHOLDER_AMOUNT: 'e.g. 49.99',
  SUBS_PLACEHOLDER_DAY: 'e.g. 1',
  SUBS_PLACEHOLDER_MONTH: 'e.g. 5',
  SUBS_PLACEHOLDER_YEAR: 'e.g. 2026',
  SUBS_INVALID_DATE: 'Enter a valid next billing date that is today or later.',

  // ─── Goals Screen Labels ────────────────────────────────
  GOALS_HEADER: 'Goals',
  GOALS_SUBTITLE: 'Track your budget targets',
  GOALS_EMPTY_TITLE: 'No budget goals yet',
  GOALS_EMPTY_DESC: 'Create budgets for your categories to start tracking spending goals.',
  GOALS_ON_TRACK_BADGE: 'On Track',
  GOALS_NEAR_LIMIT_BADGE: 'Near Limit',
  GOALS_EXCEEDED_BADGE: 'Exceeded',
  GOALS_TOTAL_BUDGETED: 'Total Budgeted',
  GOALS_ACTUAL_SPENT: 'Actual Spent',
  GOALS_YOUR_BUDGETS: 'Your Budgets',
  GOALS_NEW_BUDGET: 'New Budget Goal',
  GOALS_BUDGET_AMOUNT: 'Budget Amount',
  GOALS_CREATE: 'Create Goal',
  GOALS_CREATING: 'Creating…',
  GOALS_EDIT_BUDGET: 'Edit Budget',
  GOALS_SPENT_OF: 'spent of',
  GOALS_DELETE_BUDGET: 'Delete Budget',
  GOALS_PLACEHOLDER_AMOUNT: 'e.g. 500',
  GOALS_TRACKED: 'tracked',
  GOALS_EXCEEDED_LABEL: 'exceeded',

  // ─── Swipeable / TransactionCard ────────────────────────
  ACTION_EDIT: 'Edit',
  ACTION_SPLIT_BILL: 'Split Bill',
  ACTION_DELETE: 'Delete',
  DELETE_TRANSACTION: 'Delete Transaction',
  DELETE_TRANSACTION_CONFIRM: 'Delete',
  AMOUNT_LABEL: 'Amount',

  // ─── Stock Watchlist ────────────────────────────────────
  STOCK_OWNED: 'OWNED',
  STOCK_OWN: 'Own',
  STOCK_CURRENT_PRICE: 'Current price',
  STOCK_NUM_SHARES: 'Number of Shares',
  STOCK_AVG_BUY: 'Average Buy Price',
  STOCK_DEFAULTS_CURRENT: 'defaults to current',
  STOCK_ESTIMATED_VALUE: 'Estimated Value',
  STOCK_ADDING: 'Adding...',
  STOCK_ADD_PORTFOLIO: 'Add to Portfolio',
  STOCK_ADD: 'Add Stock',
  STOCK_SEARCH: 'Search stocks...',
  STOCK_NO_RESULTS: 'No stocks found for',
  STOCK_REMOVE_TITLE: 'Remove',
  STOCK_REMOVE_DESC: 'will be removed from your watchlist.',
  STOCK_REMOVE: 'Remove',

  // ─── Payments / Upcoming ────────────────────────────────
  PAYMENTS_IN_NEXT: 'payment(s) in next',
  MONTH_SINGULAR: 'month',
  MONTHS_PLURAL: 'months',

  // ─── Language ───────────────────────────────────────────
  LANG_ENGLISH: 'English',
  LANG_ARABIC: 'العربية',

  // ─── Category Group ─────────────────────────────────────
  CREATE_GROUP_PLACEHOLDER: 'e.g. Side Hustle, Kids, Fitness',
  SUBCATEGORY_PLACEHOLDER: 'Subcategory name',

  // ─── Goal Insights ──────────────────────────────────────
  INSIGHT_EXCEEDED: '{name} exceeded target by {amount}',
  INSIGHT_NEAR_LIMIT: '{name} is at {percent}% of target',
  INSIGHT_WITHIN_BUDGET: '{name} remains within budget',
  INSIGHT_CATEGORIES_ON_TRACK: '{count} categories remain within budget',
  GOALS_OVER_BY: 'Over by {amount}',
  GOALS_REMAINING: '{amount} left',

  // ─── RTL / Profile / Auth additions ────────────────────────
  FIRST_NAME_LABEL: 'First Name',
  FIRST_NAME_PLACEHOLDER: 'John',
  LAST_NAME_LABEL: 'Last Name',
  LAST_NAME_PLACEHOLDER: 'Doe',
  BIRTHDATE_PLACEHOLDER: 'Select your birthday',
  AUTH_NO_ACCOUNT: "Don't have an account?",
  AUTH_SIGN_UP: 'Sign up',
  AUTH_HAVE_ACCOUNT: 'Already have an account?',
  AUTH_SIGN_IN_LINK: 'Sign in',
  AUTH_ERROR_BIRTHDAY_REQUIRED: 'Please select your birthday',
  NEW_GROUP: 'New Group',
  NO_CATEGORIES_AVAILABLE: 'No categories available',
  EDIT_PROFILE: 'Edit Profile',
  FULL_NAME_AR_HINT: 'Write your name in Arabic',
  NAME_AR_LABEL: 'Arabic Name',
  NAME_AR_PLACEHOLDER: 'اكتب اسمك بالعربي',
  NAME_AR_SIGNUP_LABEL: 'Arabic Name (optional)',
  BIRTHDATE: 'Date of Birth',
  SAVE_PROFILE: 'Save',
  AUTH_SIGN_IN: 'Sign In',
  AUTH_CREATE_ACCOUNT: 'Create Account',
  YOU_PAGE_TITLE: 'You',
  CONTACT_US: 'Contact Us',
  GOAL_SINGULAR: 'goal',
  ACCOUNT_NAME_PLACEHOLDER: 'Account name',
  ACCOUNT_BALANCE_PLACEHOLDER: 'Opening balance (0.00)',
  OF: 'of',
  // ─── Profile sections ────────────────────────────────────────
  PROFILE_SECTION_PROFILE: 'Profile',
  PROFILE_SECTION_AUTOMATION: 'Automation',
  PROFILE_SECTION_DATA: 'Data & Privacy',
  PROFILE_SECTION_ABOUT: 'About',
  PROFILE_SECTION_ACCOUNT: 'Account',
  PROFILE_APP_VERSION: 'Version',
  PROFILE_MANAGE_ACCOUNTS: 'Accounts & Wallets',
  PROFILE_WHATSAPP_ROW: 'WhatsApp Import',
  PROFILE_SMS_ROW: 'SMS Auto-Import',
  PROFILE_DELETED: 'Deleted Transactions',
  PROFILE_CONTACT_US: 'Contact Support',

  // ─── Profile — WhatsApp Support ─────────────────────────
  SUPPORT_CHAT_TITLE: 'Need a hand?',
  SUPPORT_CHAT_SUBTITLE: 'Chat with us on WhatsApp — pick a topic to start',
  SUPPORT_CHAT_BUTTON: 'Chat on WhatsApp',
  SUPPORT_TOPIC_CATEGORIZE_SMS: 'Help me categorize my recent SMS transactions',
  SUPPORT_TOPIC_ADD_TRANSACTIONS: 'Help me add some transactions',
  SUPPORT_TOPIC_BUDGET: 'Help me set up a budget',
  SUPPORT_TOPIC_PLAN: 'Question about my plan / billing',
  SUPPORT_TOPIC_OTHER: 'Something else',

  // ─── Welcome Screen ─────────────────────────────────────
  WELCOME_BRAND: 'SANAD',
  WELCOME_HEADLINE: 'Your Money,\nUnder Control',
  WELCOME_TAGLINE: 'Track spending, hit your goals, and get AI-powered insights — designed for MENA.',
  WELCOME_FEATURE_DASHBOARD_TITLE: 'Smart Dashboard',
  WELCOME_FEATURE_DASHBOARD_DESC: 'Real-time balance, income & spending',
  WELCOME_FEATURE_AI_TITLE: 'AI Financial Assistant',
  WELCOME_FEATURE_AI_DESC: 'Personalized insights from your data',
  WELCOME_FEATURE_SCAN_TITLE: 'Receipt Scanning & SMS',
  WELCOME_FEATURE_SCAN_DESC: 'Auto-log transactions instantly',
  WELCOME_GET_STARTED: "Get Started — It's Free",
  WELCOME_SIGN_IN: 'Sign In',
  WELCOME_EMAIL_AVAILABLE: 'Email sign-in available',

  // ─── Forgot Password Extras ─────────────────────────────
  FORGOT_PASSWORD_CHECK_EMAIL: 'Check your email',
  FORGOT_PASSWORD_CHECK_EMAIL_DESC: 'We sent a password reset link to',
  FORGOT_PASSWORD_SENDING: 'Sending…',
  COMMON_BACK_ARROW: '← Back',
  COMMON_BACK: 'Back',
  AUTH_BACK_TO_SIGN_IN: 'Back to Sign In',

  // ─── Login / Auth Form Extras ───────────────────────────
  AUTH_WELCOME_BACK_HEADLINE: 'Welcome back',
  AUTH_SIGNIN_SUBTITLE: 'Sign in to your account',
  AUTH_GET_STARTED_HEADLINE: 'Get started',
  AUTH_SIGNUP_SUBTITLE: 'Create your free account',
  AUTH_FORGOT_SHORT: 'Forgot?',
  AUTH_LABEL_EMAIL: 'EMAIL',
  AUTH_LABEL_PASSWORD: 'PASSWORD',
  AUTH_LABEL_FIRST_NAME: 'FIRST NAME',
  AUTH_LABEL_LAST_NAME: 'LAST NAME',
  AUTH_LABEL_BIRTHDAY: 'BIRTHDAY',
  AUTH_LABEL_PHONE: 'PHONE NUMBER',
  AUTH_EMAIL_PLACEHOLDER: 'you@example.com',
  AUTH_FIRST_NAME_PLACEHOLDER: 'John',
  AUTH_LAST_NAME_PLACEHOLDER: 'Doe',
  AUTH_BIRTHDAY_PLACEHOLDER: 'Select your birthday',
  AUTH_PHONE_PLACEHOLDER: '+966 5X XXX XXXX',
  AUTH_PASSWORD_MIN: 'Min. 8 characters',
  AUTH_OR_CONTINUE: 'or continue with',
  AUTH_BIRTHDAY_MODAL_TITLE: 'Birthday',
  AUTH_CONFIRM: 'Confirm',
  AUTH_LEGAL_PREFIX: 'By continuing, you agree to our',
  AUTH_LEGAL_TERMS: 'Terms',
  AUTH_LEGAL_AND: 'and',
  AUTH_LEGAL_PRIVACY: 'Privacy Policy',

  // ─── Country Names (Onboarding) ─────────────────────────
  COUNTRY_SA: 'Saudi Arabia',
  COUNTRY_AE: 'UAE',
  COUNTRY_EG: 'Egypt',
  COUNTRY_KW: 'Kuwait',
  COUNTRY_QA: 'Qatar',
  COUNTRY_BH: 'Bahrain',
  COUNTRY_OM: 'Oman',
  COUNTRY_JO: 'Jordan',

  // ─── Profile – Language Alert ───────────────────────────
  LANG_CHANGED_TITLE: 'Language Changed',
  LANG_CHANGED_DESC: 'Restart the app to fully apply the new language layout.',

  // ─── Split Event Extras ─────────────────────────────────
  SPLIT_STATUS_SETTLED: 'Settled',
  SPLIT_STATUS_OPEN: 'Open',
  SPLIT_ITEM_NAME_PLACEHOLDER: 'Item {index} name',

  // ─── Trash Extras ───────────────────────────────────────
  TRASH_DELETE_CONFIRM_TEMPLATE: '{label} will be gone forever. Continue?',

  // ─── Subscription Category Filter Labels ────────────────
  SUB_CAT_STREAMING: 'Streaming',
  SUB_CAT_MUSIC: 'Music',
  SUB_CAT_TELECOM: 'Telecom',
  SUB_CAT_CLOUD: 'Cloud',
  SUB_CAT_PRODUCTIVITY: 'Productivity',
  SUB_CAT_GAMING: 'Gaming',
  SUB_CAT_SHOPPING: 'Shopping',
  SUB_CAT_FITNESS: 'Fitness',
  SUB_CAT_SECURITY: 'Security',
  SUB_CAT_DELIVERY: 'Delivery',
  SUB_CAT_INSURANCE: 'Insurance',
  SUB_CAT_OTHER: 'Other',
} as const;
