-- Migration 032: Convert emoji icon strings to Lucide icon names
-- for all default categories and category groups.
-- Non-default (user-created) categories are left untouched.

-- ─── Category Groups ─────────────────────────────────────────────────────────

UPDATE category_groups SET icon = CASE taxonomy_key
  WHEN 'income'                    THEN 'wallet'
  WHEN 'bills_utilities'           THEN 'receipt'
  WHEN 'housing_home'              THEN 'house'
  WHEN 'food_dining'               THEN 'utensils-crossed'
  WHEN 'transport'                 THEN 'car'
  WHEN 'shopping'                  THEN 'shopping-bag'
  WHEN 'health_medical'            THEN 'heart-pulse'
  WHEN 'education'                 THEN 'graduation-cap'
  WHEN 'family_children'           THEN 'users'
  WHEN 'entertainment_lifestyle'   THEN 'clapperboard'
  WHEN 'subscriptions_digital'     THEN 'smartphone-nfc'
  WHEN 'savings_goals'             THEN 'piggy-bank'
  WHEN 'investments'               THEN 'candlestick-chart'
  WHEN 'debt_obligations'          THEN 'credit-card'
  WHEN 'travel'                    THEN 'plane'
  WHEN 'religion_charity_social'   THEN 'heart-handshake'
  WHEN 'business_work_expenses'    THEN 'briefcase-business'
  WHEN 'pets'                      THEN 'paw-print'
  WHEN 'miscellaneous'             THEN 'boxes'
  WHEN 'transfers'                 THEN 'arrow-left-right'
  ELSE icon
END
WHERE taxonomy_key IS NOT NULL AND is_default = true;

-- ─── Categories (subcategories) ──────────────────────────────────────────────

UPDATE categories SET icon = CASE taxonomy_key
  -- Income
  WHEN 'salary'                    THEN 'briefcase'
  WHEN 'bonus'                     THEN 'award'
  WHEN 'freelance'                 THEN 'laptop'
  WHEN 'business_profit'           THEN 'store'
  WHEN 'rental_income'             THEN 'building-2'
  WHEN 'investment_income'         THEN 'chart-column'
  WHEN 'family_support_in'         THEN 'hand-coins'
  WHEN 'gift_received'             THEN 'gift'
  WHEN 'refund_rebate'             THEN 'rotate-ccw'
  WHEN 'other_income'              THEN 'plus-circle'
  -- Bills & Utilities
  WHEN 'electricity'               THEN 'zap'
  WHEN 'water'                     THEN 'droplets'
  WHEN 'gas'                       THEN 'flame'
  WHEN 'internet'                  THEN 'wifi'
  WHEN 'mobile'                    THEN 'smartphone'
  WHEN 'tv_satellite'              THEN 'tv'
  WHEN 'building_fees'             THEN 'building'
  WHEN 'government_services'       THEN 'landmark'
  WHEN 'absher'                    THEN 'smartphone'
  WHEN 'fawry'                     THEN 'receipt'
  WHEN 'e_gov_egypt'               THEN 'landmark'
  -- Housing & Home
  WHEN 'rent'                      THEN 'key'
  WHEN 'mortgage'                  THEN 'landmark'
  WHEN 'home_maintenance'          THEN 'hammer'
  WHEN 'furniture'                 THEN 'sofa'
  WHEN 'home_appliances'           THEN 'refrigerator'
  WHEN 'cleaning_supplies'         THEN 'spray-can'
  WHEN 'home_decor'                THEN 'lamp'
  WHEN 'security_services'         THEN 'shield'
  WHEN 'domestic_worker'           THEN 'user-round'
  -- Food & Dining
  WHEN 'groceries'                 THEN 'shopping-cart'
  WHEN 'bakery'                    THEN 'croissant'
  WHEN 'meat_seafood'              THEN 'fish'
  WHEN 'restaurants'               THEN 'chef-hat'
  WHEN 'cafes_coffee'              THEN 'coffee'
  WHEN 'food_delivery'             THEN 'bike'
  WHEN 'hungerstation'             THEN 'smartphone'
  WHEN 'jahez'                     THEN 'bike'
  WHEN 'marsool'                   THEN 'package'
  WHEN 'talabat'                   THEN 'shopping-bag'
  WHEN 'elmenus'                   THEN 'utensils'
  WHEN 'snacks_sweets'             THEN 'ice-cream-cone'
  WHEN 'water_beverages'           THEN 'cup-soda'
  -- Transport
  WHEN 'fuel'                      THEN 'fuel'
  WHEN 'uber_taxi'                 THEN 'car-taxi-front'
  WHEN 'careem'                    THEN 'car-taxi-front'
  WHEN 'public_transport'          THEN 'bus'
  WHEN 'parking'                   THEN 'parking-circle'
  WHEN 'tolls'                     THEN 'road'
  WHEN 'car_maintenance'           THEN 'wrench'
  WHEN 'car_insurance'             THEN 'shield-check'
  WHEN 'registration_licensing'    THEN 'file-badge'
  WHEN 'car_rental'                THEN 'car-front'
  -- Shopping
  WHEN 'fashion'                   THEN 'shirt'
  WHEN 'shoes'                     THEN 'footprints'
  WHEN 'bags_accessories'          THEN 'briefcase'
  WHEN 'jewelry'                   THEN 'gem'
  WHEN 'watches'                   THEN 'watch'
  WHEN 'electronics'               THEN 'smartphone'
  WHEN 'general_shopping'          THEN 'package'
  WHEN 'gifts'                     THEN 'gift'
  -- Health & Medical
  WHEN 'doctor_visits'             THEN 'stethoscope'
  WHEN 'medicines'                 THEN 'pill'
  WHEN 'lab_tests'                 THEN 'flask-conical'
  WHEN 'hospital'                  THEN 'hospital'
  WHEN 'dental'                    THEN 'smile-plus'
  WHEN 'therapy_fitness'           THEN 'activity'
  WHEN 'health_insurance'          THEN 'shield-plus'
  -- Education
  WHEN 'school_fees'               THEN 'school'
  WHEN 'university'                THEN 'building-library'
  WHEN 'courses_training'          THEN 'book-open'
  WHEN 'books_supplies'            THEN 'book'
  WHEN 'tutoring'                  THEN 'user-round'
  WHEN 'exam_fees'                 THEN 'file-pen-line'
  WHEN 'school_transport'          THEN 'bus-front'
  WHEN 'language_learning'         THEN 'languages'
  -- Family & Children
  WHEN 'childcare'                 THEN 'baby'
  WHEN 'baby_supplies'             THEN 'baby'
  WHEN 'kids_clothing'             THEN 'shirt'
  WHEN 'allowances'                THEN 'banknote'
  WHEN 'family_support_out'        THEN 'hand-heart'
  WHEN 'school_needs'              THEN 'backpack'
  WHEN 'kids_activities'           THEN 'toy-brick'
  WHEN 'maternity'                 THEN 'heart'
  WHEN 'elderly_care'              THEN 'heart-handshake'
  -- Entertainment & Lifestyle
  WHEN 'cinema_events'             THEN 'ticket'
  WHEN 'gaming'                    THEN 'gamepad-2'
  WHEN 'hobbies'                   THEN 'palette'
  WHEN 'beauty_grooming'           THEN 'sparkles'
  WHEN 'sports_clubs'              THEN 'dumbbell'
  WHEN 'social_outings'            THEN 'party-popper'
  WHEN 'smoking_shisha'            THEN 'cigarette'
  WHEN 'laundry'                   THEN 'washing-machine'
  -- Subscriptions & Digital
  WHEN 'netflix'                   THEN 'monitor-play'
  WHEN 'shahid_vip'                THEN 'tv'
  WHEN 'disney_plus'               THEN 'film'
  WHEN 'spotify'                   THEN 'music-4'
  WHEN 'youtube_premium'           THEN 'youtube'
  WHEN 'anghami'                   THEN 'music'
  WHEN 'icloud_storage'            THEN 'cloud'
  WHEN 'chatgpt_ai_tools'          THEN 'bot'
  WHEN 'vpn_security'              THEN 'shield-ellipsis'
  WHEN 'other_digital'             THEN 'globe'
  -- Savings & Goals
  WHEN 'emergency_fund'            THEN 'shield-alert'
  WHEN 'general_savings'           THEN 'wallet-cards'
  WHEN 'home_goal'                 THEN 'house'
  WHEN 'car_goal'                  THEN 'car'
  WHEN 'wedding_goal'              THEN 'heart-handshake'
  WHEN 'education_goal'            THEN 'graduation-cap'
  WHEN 'travel_goal'               THEN 'plane'
  WHEN 'hajj_umrah_goal'           THEN 'moon-star'
  -- Investments
  WHEN 'stocks'                    THEN 'chart-line'
  WHEN 'etfs_funds'                THEN 'chart-pie'
  WHEN 'crypto'                    THEN 'bitcoin'
  WHEN 'gold_silver'               THEN 'coins'
  WHEN 'real_estate_investment'    THEN 'building-2'
  WHEN 'private_business'          THEN 'store'
  WHEN 'retirement'                THEN 'hourglass'
  -- Debt & Obligations
  WHEN 'credit_card_payment'       THEN 'credit-card'
  WHEN 'personal_loan'             THEN 'hand-coins'
  WHEN 'mortgage_payment'          THEN 'house-plus'
  WHEN 'car_loan'                  THEN 'car-front'
  WHEN 'installments_bnpl'         THEN 'calendar-sync'
  WHEN 'tabby'                     THEN 'smartphone-nfc'
  WHEN 'tamara'                    THEN 'smartphone-nfc'
  WHEN 'taxes_fees'                THEN 'receipt-text'
  WHEN 'legal_support'             THEN 'scale'
  WHEN 'alimony_support'           THEN 'hand-heart'
  -- Travel
  WHEN 'flights'                   THEN 'plane-takeoff'
  WHEN 'hotels'                    THEN 'hotel'
  WHEN 'visa_fees'                 THEN 'passport'
  WHEN 'travel_transport'          THEN 'train-front'
  WHEN 'travel_food'               THEN 'utensils'
  WHEN 'travel_shopping'           THEN 'shopping-bag'
  WHEN 'travel_insurance'          THEN 'shield-check'
  WHEN 'hajj_umrah_trip'           THEN 'moon-star'
  -- Religion / Charity / Social
  WHEN 'zakat'                     THEN 'hand-coins'
  WHEN 'sadaqah'                   THEN 'heart'
  WHEN 'mosque_community'          THEN 'building'
  WHEN 'eid_social_giving'         THEN 'gift'
  WHEN 'family_occasions'          THEN 'users'
  WHEN 'funeral_support'           THEN 'flower-2'
  WHEN 'religious_courses'         THEN 'book-heart'
  WHEN 'qurbani'                   THEN 'beef'
  WHEN 'ramadan_supplies'          THEN 'moon-star'
  -- Business / Work Expenses
  WHEN 'office_supplies'           THEN 'paperclip'
  WHEN 'software_tools'            THEN 'monitor-cog'
  WHEN 'business_travel'           THEN 'plane'
  WHEN 'marketing_ads'             THEN 'megaphone'
  WHEN 'shipping_logistics'        THEN 'truck'
  WHEN 'professional_services'     THEN 'users-round'
  WHEN 'coworking_office_rent'     THEN 'building'
  WHEN 'internet_phone_work'       THEN 'smartphone'
  -- Pets
  WHEN 'pet_food'                  THEN 'bone'
  WHEN 'vet'                       THEN 'stethoscope'
  WHEN 'pet_supplies'              THEN 'package'
  WHEN 'grooming'                  THEN 'scissors'
  WHEN 'boarding'                  THEN 'house'
  WHEN 'pet_toys'                  THEN 'toy-brick'
  -- Miscellaneous
  WHEN 'cash_withdrawal'           THEN 'banknote'
  WHEN 'fees_commissions'          THEN 'receipt'
  WHEN 'fines_penalties'           THEN 'octagon-alert'
  WHEN 'unexpected_expense'        THEN 'triangle-alert'
  WHEN 'uncategorized'             THEN 'circle-help'
  -- Transfers
  WHEN 'between_accounts'          THEN 'repeat'
  WHEN 'cash_to_bank'              THEN 'landmark'
  WHEN 'bank_to_cash'              THEN 'wallet'
  WHEN 'wallet_top_up'             THEN 'smartphone'
  WHEN 'savings_transfer'          THEN 'piggy-bank'
  WHEN 'investment_transfer'       THEN 'candlestick-chart'
  ELSE icon
END
WHERE taxonomy_key IS NOT NULL AND is_default = true;
